'use client';
import {useMemo,useState} from 'react';
import {Search,BellRing,Wifi,MapPin,MoreHorizontal,X,CreditCard,Instagram,Star,ChevronLeft,ChevronRight,Globe2,Menu} from 'lucide-react';
import type {QrMenuProduct,QrMenuRestaurant} from '../../lib/qr-menu/types';
import './makarilla-customer-premium.css';
const categoryEmoji:Record<string,string>={pastas:'🍝','chicken-pastas':'🍗',salads:'🥗',wraps:'🌯',desserts:'🍰',drinks:'🥤'};
export function MakarillaCustomerPremium({restaurant}:{restaurant:QrMenuRestaurant}){
 const[query,setQuery]=useState('');const[cat,setCat]=useState('all');const[selected,setSelected]=useState<QrMenuProduct|null>(null);const[drawer,setDrawer]=useState(false);
 const active=useMemo(()=>restaurant.products.filter(p=>p.isActive),[restaurant.products]);const cats=restaurant.categories.filter(c=>c.isActive);const products=useMemo(()=>active.filter(p=>(cat==='all'||p.categoryId===cat)&&`${p.name} ${p.description}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'))),[active,cat,query]);const hero=active.find(p=>p.isFeatured)||active[0];const promo=active[1]||hero;
 const ProductRow=({p}:{p:QrMenuProduct})=><button className="mkc-product" onClick={()=>setSelected(p)}><img src={p.image} alt={p.name}/><div className="mkc-product-copy"><div className="mkc-name-line"><strong>{p.name}</strong>{p.isFeatured&&<em>Şefin Özeli</em>}</div><p>{p.description}</p></div><b>₺{p.price}</b></button>;
 return <main className="mkc-stage" style={{'--menu-accent':restaurant.theme.accent} as React.CSSProperties}><section className="mkc-app">
 <header className="mkc-topbar"><img className="mkc-logo" src={restaurant.logo} alt={restaurant.name}/><div className="mkc-top-actions"><button className="mkc-lang"><Globe2/>TR⌄</button><button onClick={()=>setDrawer(true)}><Menu/></button></div></header>
 {hero&&<section className="mkc-hero"><img src={hero.image} alt={hero.name}/><div className="mkc-hero-shade"/><div className="mkc-hero-copy"><small>ŞEFİN ÖZELİ</small><h1>{hero.name}</h1><p>{hero.description}</p><button onClick={()=>document.getElementById('menu-start')?.scrollIntoView({behavior:'smooth'})}>Menüyü Keşfet <ChevronRight/></button></div></section>}
 <section className="mkc-body" id="menu-start"><label className="mkc-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün, kategori veya içerik ara..."/></label><nav className="mkc-categories"><button className={cat==='all'?'is-active':''} onClick={()=>setCat('all')}><span>🍽️</span><small>Tümü</small></button>{cats.map(c=><button key={c.id} className={cat===c.id?'is-active':''} onClick={()=>setCat(c.id)}><span>{categoryEmoji[c.id]||'🍴'}</span><small>{c.name}</small></button>)}</nav>
 {!query&&cat==='all'&&promo&&<section className="mkc-promo"><div><small>TAZE MALZEME</small><strong>GERÇEK İTALYAN LEZZETİ</strong><span>İTALYAN MUTFAĞI</span></div><img src={promo.image} alt="İtalyan mutfağı"/></section>}
 {query||cat!=='all'?<section className="mkc-category-block"><div className="mkc-section-head"><h2>{query?'Arama Sonuçları':cats.find(c=>c.id===cat)?.name}</h2><span>{products.length} ürün</span></div><div className="mkc-product-list">{products.map(p=><ProductRow key={p.id} p={p}/>)}</div></section>:cats.map(c=>{const list=active.filter(p=>p.categoryId===c.id).slice(0,4);if(!list.length)return null;return <section className="mkc-category-block" key={c.id}><div className="mkc-section-head"><h2>{c.name}</h2><button onClick={()=>setCat(c.id)}>Tümünü Gör <ChevronRight/></button></div><div className="mkc-product-list">{list.map(p=><ProductRow key={p.id} p={p}/>)}</div></section>})}</section>
 <nav className="mkc-quickbar"><button className="primary"><BellRing/><span>Garson</span></button><button><Wifi/><span>Wi‑Fi</span></button><button><MapPin/><span>Yol Tarifi</span></button><button onClick={()=>setDrawer(true)}><MoreHorizontal/><span>Daha Fazla</span></button></nav></section>
 {selected&&<div className="mkc-detail"><section><header><button onClick={()=>setSelected(null)}><ChevronLeft/></button></header><div className="mkc-detail-image"><img src={selected.image} alt={selected.name}/></div><article>{selected.isFeatured&&<div className="mkc-detail-badge">Şefin Özeli</div>}<div className="mkc-detail-title"><h2>{selected.name}</h2><b>₺{selected.price}</b></div><p className="mkc-detail-desc">{selected.description}</p><h3>Ürün Bilgileri</h3><div className="mkc-story"><div>🍴</div><p><b>Gerçek İtalyan Lezzeti</b><span>Taze malzemeler ve özenle hazırlanan tarif.</span></p></div>{selected.allergens?.length?<div className="mkc-allergen"><b>Alerjen Bilgisi</b><span>{selected.allergens.join(', ')}</span></div>:null}<button className="mkc-back-menu" onClick={()=>setSelected(null)}>← Menüye Dön</button></article></section></div>}
 {drawer&&<div className="mkc-drawer-backdrop" onClick={()=>setDrawer(false)}><aside className="mkc-drawer" onClick={e=>e.stopPropagation()}><button className="mkc-close" onClick={()=>setDrawer(false)}><X/></button><img src={restaurant.logo} alt={restaurant.name}/><button><BellRing/>Garson Çağır</button><button><Wifi/>Wi‑Fi Bilgileri</button><button><CreditCard/>IBAN</button><button><MapPin/>Yol Tarifi</button><button><Instagram/>Sosyal Medya</button><button><Star/>Yorum Yap</button></aside></div>}
 </main>;
}