'use client';
import {useMemo,useState} from 'react';
import {Search,BellRing,Wifi,MapPin,MoreHorizontal,X,CreditCard,Instagram,Star,ChevronLeft,SlidersHorizontal} from 'lucide-react';
import type {QrMenuProduct,QrMenuRestaurant} from '../../lib/qr-menu/types';
import './makarilla-customer-premium.css';
const categoryEmoji:Record<string,string>={pastas:'🍝','chicken-pastas':'🍗',salads:'🥗',wraps:'🌯',desserts:'🍰',drinks:'🥤'};
export function MakarillaCustomerPremium({restaurant}:{restaurant:QrMenuRestaurant}){
 const[query,setQuery]=useState('');const[cat,setCat]=useState('all');const[selected,setSelected]=useState<QrMenuProduct|null>(null);const[drawer,setDrawer]=useState(false);
 const active=useMemo(()=>restaurant.products.filter(p=>p.isActive),[restaurant.products]);const cats=restaurant.categories.filter(c=>c.isActive);
 const products=useMemo(()=>active.filter(p=>(cat==='all'||p.categoryId===cat)&&`${p.name} ${p.description}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR'))),[active,cat,query]);
 const popular=active.filter(p=>p.isFeatured).length?active.filter(p=>p.isFeatured):active;
 const ProductCard=({p}:{p:QrMenuProduct})=><button className="mkc-product" onClick={()=>setSelected(p)}><div className="mkc-product-image"><img src={p.image} alt={p.name}/>{p.isFeatured&&<span>Popüler</span>}</div><div className="mkc-product-info"><strong>{p.name}</strong><p>{p.description}</p><div><b>₺{p.price}</b><i>＋</i></div></div></button>;
 return <main className="mkc-stage"><section className="mkc-app">
  <header className="mkc-topbar"><div className="mkc-brand"><img src={restaurant.logo} alt={restaurant.name}/><div><b>{restaurant.name}</b><small>Evde İtalyan Makarnası</small></div></div><button className="mkc-bell"><BellRing size={18}/></button></header>
  <section className="mkc-welcome"><small>Menü</small><h1>Bugün ne yemek istersiniz?</h1></section>
  <section className="mkc-tools"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Menüde ara"/></label><button><SlidersHorizontal size={19}/></button></section>
  <nav className="mkc-categories"><button className={cat==='all'?'is-active':''} onClick={()=>setCat('all')}><span>🍽️</span><small>Tümü</small></button>{cats.map(c=><button key={c.id} className={cat===c.id?'is-active':''} onClick={()=>setCat(c.id)}><span>{categoryEmoji[c.id]||'🍴'}</span><small>{c.name}</small></button>)}</nav>
  <section className="mkc-body">{query||cat!=='all'?<><div className="mkc-section-head"><h2>{query?'Arama Sonuçları':cats.find(c=>c.id===cat)?.name}</h2><span>{products.length} ürün</span></div><div className="mkc-grid">{products.map(p=><ProductCard key={p.id} p={p}/>)}</div></>:<>{cats.map((c,ci)=>{const list=(ci===0?popular:active.filter(p=>p.categoryId===c.id)).slice(0,4);if(!list.length)return null;return <section className="mkc-category-block" key={c.id}><div className="mkc-section-head"><h2>{ci===0?'Popüler '+c.name:c.name}</h2><button onClick={()=>setCat(c.id)}>Tümünü gör</button></div><div className="mkc-grid">{list.map(p=><ProductCard key={p.id} p={p}/>)}</div></section>})}</>}</section>
  <nav className="mkc-quickbar"><button className="primary"><BellRing/><span>Garson</span></button><button><Wifi/><span>Wi‑Fi</span></button><button><MapPin/><span>Yol Tarifi</span></button><button onClick={()=>setDrawer(true)}><MoreHorizontal/><span>Daha Fazla</span></button></nav>
 </section>
 {selected&&<div className="mkc-detail"><section><header><button onClick={()=>setSelected(null)}><ChevronLeft/></button><span>Ürün Detayı</span><button>♡</button></header><div className="mkc-detail-image"><img src={selected.image} alt={selected.name}/></div><article><small>MAKARILLA</small><h2>{selected.name}</h2><div className="mkc-detail-price">₺{selected.price}</div><h3>Açıklama</h3><p>{selected.description}</p>{selected.allergens?.length?<><h3>Alerjenler</h3><div className="mkc-tags">{selected.allergens.map(a=><span key={a}>{a}</span>)}</div></>:null}<div className="mkc-nutrition"><span>🔥 420 kcal</span><span>🌾 36g</span><span>🥩 28g</span><span>💧 18g</span></div></article></section></div>}
 {drawer&&<div className="mkc-drawer-backdrop" onClick={()=>setDrawer(false)}><aside className="mkc-drawer" onClick={e=>e.stopPropagation()}><button className="mkc-close" onClick={()=>setDrawer(false)}><X/></button><img src={restaurant.logo} alt={restaurant.name}/><button><BellRing/>Garson Çağır</button><button><Wifi/>Wi-Fi Bilgileri</button><button><CreditCard/>IBAN</button><button><MapPin/>Yol Tarifi</button><button><Instagram/>Sosyal Medya</button><button><Star/>Yorum Yap</button></aside></div>}
 </main>
}