import type { QrMenuRestaurant } from './types';

export const makarillaRestaurant: QrMenuRestaurant = {
  id: 'makarilla',
  slug: 'makarilla',
  name: 'Makarilla',
  shortName: 'makarilla',
  tagline: 'Evde İtalyan Makarnası',
  coverImage: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=88',
  theme: {
    accent: '#C94637',
    background: '#FBF7F2',
    surface: '#FFFFFF',
    text: '#2A2926',
    muted: '#847B72',
    radius: 16,
  },
  branch: {
    id: 'makarilla-karsiyaka',
    name: 'Karşıyaka',
    address: 'Karşıyaka',
    city: 'İzmir',
    openingHours: 'Her gün 11:00 – 23:30',
  },
  categories: [
    { id: 'pastas', name: 'Makarnalar', sortOrder: 1, isActive: true },
    { id: 'chicken-pastas', name: 'Tavuklu Makarnalar', sortOrder: 2, isActive: true },
    { id: 'salads', name: 'Salatalar', sortOrder: 3, isActive: true },
    { id: 'wraps', name: 'Wraplar', sortOrder: 4, isActive: true },
    { id: 'desserts', name: 'Tatlılar', sortOrder: 5, isActive: true },
    { id: 'drinks', name: 'İçecekler', sortOrder: 6, isActive: true },
  ],
  products: [
    {
      id: 'casarecce-bolognese',
      categoryId: 'pastas',
      name: 'Casarecce Bolognese',
      description: 'Domates bazlı bolonez sos, parmesan ve taze otlarla casarecce.',
      price: 299,
      image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1000&q=88',
      allergens: ['Gluten', 'Süt'],
      isFeatured: true,
      isActive: true,
      sortOrder: 1,
    },
    {
      id: 'casarecce-kremali-mantar',
      categoryId: 'pastas',
      name: 'Casarecce Kremalı Mantar',
      description: 'Kremalı mantar sos, parmesan ve taze kekikle casarecce.',
      price: 289,
      image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1000&q=88',
      allergens: ['Gluten', 'Süt'],
      isFeatured: true,
      isActive: true,
      sortOrder: 2,
    },
    {
      id: 'penne-pesto-tavuk',
      categoryId: 'chicken-pastas',
      name: 'Penne Pesto Tavuk',
      description: 'Izgara tavuk parçaları, pesto sos ve parmesan ile penne.',
      price: 319,
      image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?auto=format&fit=crop&w=1000&q=88',
      allergens: ['Gluten', 'Süt'],
      isFeatured: true,
      isActive: true,
      sortOrder: 3,
    },
    {
      id: 'penne-alfredo-tavuk',
      categoryId: 'chicken-pastas',
      name: 'Penne Alfredo Tavuk',
      description: 'Kremalı Alfredo sos, mantar, tavuk ve parmesan ile penne.',
      price: 319,
      image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1000&q=88',
      allergens: ['Gluten', 'Süt'],
      isFeatured: true,
      isActive: true,
      sortOrder: 4,
    },
    {
      id: 'akdeniz-salata',
      categoryId: 'salads',
      name: 'Akdeniz Salata',
      description: 'Mevsim yeşillikleri, domates, salatalık ve özel sos.',
      price: 189,
      image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1000&q=88',
      isActive: true,
      sortOrder: 5,
    },
    {
      id: 'tavuk-wrap',
      categoryId: 'wraps',
      name: 'Tavuk Wrap',
      description: 'Izgara tavuk, yeşillik ve özel sosla dürüm.',
      price: 239,
      image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1000&q=88',
      isActive: true,
      sortOrder: 6,
    },
    {
      id: 'tiramisu',
      categoryId: 'desserts',
      name: 'Tiramisu',
      description: 'Klasik İtalyan usulü tiramisu.',
      price: 159,
      image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=1000&q=88',
      allergens: ['Süt', 'Gluten'],
      isActive: true,
      sortOrder: 7,
    },
    {
      id: 'cola',
      categoryId: 'drinks',
      name: 'Coca-Cola 330 ml',
      description: 'Soğuk servis edilir.',
      price: 65,
      image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=1000&q=88',
      isActive: true,
      sortOrder: 8,
    },
  ],
};
