'use client';
import {useEffect} from 'react';

type Data={range:string;todayViews:number;periodViews:number;averageRating:number;feedbackCount:number;serviceCalls:number;dailyViews:{day:string;count:number}[];topProducts:{id:string;name:string;image:string;price:number;views:number}[]};
const tr=(d:string)=>new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short'}).format(new Date(`${d}T12:00:00`));
export default function AdminStatsEnhancer(){
 useEffect(()=>{
  if(!location.pathname.startsWith('/admin/'))return;let dead=false;
  const run=()=>{const page=[...document.querySelectorAll<HTMLElement>('.qaPage')].find(x=>x.querySelector('h1')?.textContent?.trim()==='İstatistikler');if(!page||page.dataset.statsPremium==='1')return;page.dataset.statsPremium='1';page.classList.add('qaStatsPremiumPage');const slug=location.pathname.split('/')[2]||'makarilla';page.innerHTML=`<div class="qaStatsHero"><div><small>İSTATİSTİKLER</small><h1>Menünüzün Performansı</h1><p>QR menünüzün görüntülenmelerini, ürün ilgisini ve restoran içi etkileşimleri gerçek verilerle takip edin.</p></div><select aria-label="Dönem"><option value="7">Son 7 Gün</option><option value="30" selected>Son 30 Gün</option><option value="90">Son 3 Ay</option><option value="all">Tümü</option></select></div><div class="qaStatsLoading">Gerçek veriler yükleniyor…</div>`;
   const select=page.querySelector('select')!;const load=async()=>{page.classList.add('loading');try{const r=await fetch(`/api/qr-menu/${slug}/stats?range=${select.value}`,{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json() as Data;if(dead)return;render(page,d,select.value)}catch{const x=page.querySelector('.qaStatsLoading');if(x)x.textContent='İstatistik verileri şu anda yüklenemedi.'}finally{page.classList.remove('loading')}};select.addEventListener('change',load);load()};
  const render=(page:HTMLElement,d:Data,range:string)=>{page.querySelectorAll('.qaStatsContent').forEach(x=>x.remove());const wrap=document.createElement('div');wrap.className='qaStatsContent';const max=Math.max(1,...d.dailyViews.map(x=>x.count));const totalProduct=d.topProducts.reduce((s,x)=>s+x.views,0);const label=range==='7'?'Son 7 gün':range==='30'?'Son 30 gün':range==='90'?'Son 3 ay':'Tüm zamanlar';wrap.innerHTML=`<div class="qaStatsMetrics"><article><i>◉</i><div><span>${label}</span><strong>${d.periodViews.toLocaleString('tr-TR')}</strong><small>Menü görüntülenme</small></div></article><article><i>◷</i><div><span>Bugün</span><strong>${d.todayViews.toLocaleString('tr-TR')}</strong><small>Menü görüntülenme</small></div></article><article><i>★</i><div><span>Misafir Puanı</span><strong>${d.averageRating?d.averageRating.toFixed(1):'—'}</strong><small>${d.feedbackCount} geri bildirim</small></div></article><article><i>♢</i><div><span>Garson Çağrısı</span><strong>${d.serviceCalls.toLocaleString('tr-TR')}</strong><small>${label.toLocaleLowerCase('tr-TR')}</small></div></article></div><div class="qaStatsGrid"><section class="qaStatsTrend"><header><div><h2>Menü Görüntülenme Trendi</h2><p>${label} boyunca gerçek QR menü görüntülenmeleri.</p></div><b>${d.periodViews.toLocaleString('tr-TR')} görüntülenme</b></header>${d.dailyViews.length?`<div class="qaStatsBars">${d.dailyViews.map(x=>`<div><em style="height:${Math.max(5,Math.round(x.count/max*100))}%" title="${x.count} görüntülenme"></em><span>${tr(x.day)}</span><b>${x.count}</b></div>`).join('')}</div>`:'<div class="qaStatsEmpty">Bu dönemde henüz menü görüntülenme verisi yok.</div>'}</section><section class="qaStatsProducts"><header><div><h2>En Çok İncelenen Ürünler</h2><p>Ürün detay görüntülenmelerine göre.</p></div><b>${totalProduct.toLocaleString('tr-TR')} ürün inceleme</b></header>${d.topProducts.some(x=>x.views>0)?`<div class="qaStatsProductList">${d.topProducts.filter(x=>x.views>0).map((x,i)=>`<article><strong>${i+1}</strong>${x.image?`<img src="${x.image}" alt="">`:'<i>🍽</i>'}<div><b>${x.name}</b><small>${x.price.toLocaleString('tr-TR')} TL</small></div><span>${x.views} görüntülenme</span></article>`).join('')}</div>`:'<div class="qaStatsEmpty">Henüz ürün detay görüntülenmesi kaydedilmedi.</div>'}</section><aside class="qaStatsFacts"><h2>Bu ekranda ne ölçüyoruz?</h2><p>✓ QR menünün gerçek açılma sayısı</p><p>✓ Bugünkü menü görüntülenmeleri</p><p>✓ Ürün detaylarının görüntülenme sayısı</p><p>✓ QR menüden gelen geri bildirim ve puanlar</p><p>✓ Restoran içi garson çağrıları</p><small>Tekil ziyaretçi, cihaz, trafik kaynağı ve ziyaret süresi ölçülmediği için bu ekranda gösterilmez.</small></aside></div><div class="qaStatsBanner"><div><b>Verilerle daha güçlü bir menü.</b><span>Misafirlerinizin gerçekten kullandığı QR menü verilerini takip edin.</span></div><a href="/menu/${location.pathname.split('/')[2]||'makarilla'}" target="_blank">Menümü Görüntüle ↗</a></div>`;page.append(wrap)};
  run();const ob=new MutationObserver(run);ob.observe(document.body,{childList:true,subtree:true});return()=>{dead=true;ob.disconnect()}
 },[]);return null;
}
