import Image from 'next/image';
import { ArrowRight, Instagram, Mail, MessageCircle } from 'lucide-react';

export default function FinalCtaSection(){
 return <><section className="fc" id="analiz"><style>{`
 .fc{background:#031722;padding:82px 0;color:#fff}.fcS{width:min(1180px,calc(100% - 64px));margin:auto}.fcPanel{display:grid;grid-template-columns:.82fr 1.18fr;min-height:570px;border-radius:32px;overflow:hidden;background:linear-gradient(135deg,#075675,#042a3d);border:1px solid rgba(33,216,246,.18);box-shadow:0 24px 62px rgba(0,0,0,.16)}.fcCopy{padding:62px 48px;display:flex;flex-direction:column;justify-content:center}.fcK{color:#8ceafa;font-size:11px;font-weight:900;letter-spacing:2.7px}.fc h2{margin:14px 0 17px;font-size:clamp(43px,4.7vw,64px);line-height:.95;letter-spacing:-2.5px}.fc h2 span{display:block;color:#21d8f6}.fc p{max-width:500px;color:#d1e0e5;font-size:15px;line-height:1.6}.fcBtn{display:inline-flex;align-items:center;justify-content:center;gap:9px;width:max-content;margin-top:25px;padding:16px 21px;border-radius:14px;background:#21d8f6;color:#03202d;text-decoration:none;font-size:13px;font-weight:950}.fcVisual{position:relative;overflow:hidden;background:#062331}.fcVisual img{object-fit:cover;object-position:center}.fcVisual:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,#075675 0%,rgba(7,86,117,.35) 12%,transparent 34%)}.fcBadge{position:absolute;z-index:2;right:22px;bottom:22px;padding:13px 15px;border-radius:14px;background:rgba(3,23,34,.88);backdrop-filter:blur(8px);font-size:12px;font-weight:850;color:#fff;box-shadow:0 10px 28px rgba(0,0,0,.18)}.fcBadge b{display:block;color:#21d8f6;font-size:16px;margin-bottom:2px}.nf{background:#02131d;color:#fff;padding:34px 0 24px}.nfS{width:min(1180px,calc(100% - 64px));margin:auto}.nfTop{display:grid;grid-template-columns:1.2fr .8fr .8fr;gap:40px;padding-bottom:27px;border-bottom:1px solid rgba(255,255,255,.08)}.nfLogo{width:140px;height:auto}.nf p{max-width:360px;color:#8faab5;font-size:12.5px;line-height:1.5}.nfCol strong{display:block;font-size:11px;letter-spacing:1.3px;margin-bottom:10px}.nfCol a{display:flex;align-items:center;gap:7px;color:#8faab5;text-decoration:none;font-size:12px;margin:8px 0}.nfBottom{display:flex;justify-content:space-between;padding-top:18px;color:#688792;font-size:11px}.nfBottom b{color:#a7bec7}
 @media(max-width:760px){.fc{padding:40px 0 30px}.fcS{width:calc(100% - 24px)}.fcPanel{grid-template-columns:1fr;min-height:0;border-radius:22px}.fcVisual{order:-1;height:340px}.fcVisual img{object-position:center}.fcVisual:after{background:linear-gradient(180deg,transparent 62%,#075675 100%)}.fcCopy{padding:25px 19px 27px}.fc h2{font-size:36px;letter-spacing:-1.4px}.fc p{font-size:13.5px}.fcBtn{width:100%;margin-top:18px}.fcBadge{right:14px;bottom:14px}.nf{padding:27px 0 20px}.nfS{width:calc(100% - 30px)}.nfTop{grid-template-columns:1fr;gap:20px}.nfBottom{display:block;line-height:1.7}}
 `}</style><div className="fcS"><div className="fcPanel"><div className="fcCopy"><div className="fcK">ÜCRETSİZ RESTORAN ANALİZİ</div><h2>NEREDEN<span>BÜYÜYEBİLİRİZ?</span></h2><p>Menünüzü, fiyatlarınızı ve dijital satış yapınızı birlikte inceleyelim. Siparişi ve gerçek kazancı artırabilecek en güçlü fırsatları netleştirelim.</p><a className="fcBtn" href="#iletisim">Ücretsiz Analiz İstiyorum <ArrowRight size={18}/></a></div><div className="fcVisual"><Image src="/naribo-ucretsiz-analiz.png" alt="Naribo restoran performans analizi" fill sizes="(max-width:760px) 100vw, 60vw"/><div className="fcBadge"><b>SİPARİŞ + KÂRLILIK</b>Tek analiz. Net büyüme fırsatları.</div></div></div></div></section><footer className="nf" id="iletisim"><div className="nfS"><div className="nfTop"><div><Image src="/naribo-logo.png" alt="Naribo" width={265} height={110} className="nfLogo"/><p>Restoranların dijital satışını, sipariş sayısını ve gerçek kazancını birlikte büyüten büyüme ortağı.</p></div><div className="nfCol"><strong>NARİBO</strong><a href="#hizmetler">Hizmetler</a><a href="#nasil">Nasıl Çalışıyoruz?</a><a href="#naribo-modeli">Naribo Modeli</a><a href="#analiz">Ücretsiz Analiz</a></div><div className="nfCol"><strong>İLETİŞİM</strong><a href="#iletisim"><MessageCircle size={15}/> WhatsApp</a><a href="#iletisim"><Mail size={15}/> E-posta</a><a href="#iletisim"><Instagram size={15}/> Instagram</a></div></div><div className="nfBottom"><span>© 2026 <b>Naribo</b>. Tüm hakları saklıdır.</span><span>Ajansınız değil. <b>Büyüme ortağınız.</b></span></div></div></footer></>
}
