import Image from 'next/image';
import { ArrowRight, Instagram, Mail, MessageCircle } from 'lucide-react';

export default function FinalCtaSection(){
 return <><section className="fc" id="analiz"><style>{`
 .fc{background:#031722;padding:54px 0;color:#fff}.fcS{width:min(1180px,calc(100% - 64px));margin:auto}.fcPanel{position:relative;height:540px;border-radius:30px;overflow:hidden;background:#031722;border:1px solid rgba(33,216,246,.14);box-shadow:0 22px 55px rgba(0,0,0,.16)}.fcVisual{position:absolute;inset:0}.fcVisual img{object-fit:cover;object-position:center}.fcVisual:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,23,34,.98) 0%,rgba(3,23,34,.91) 30%,rgba(3,23,34,.52) 47%,rgba(3,23,34,.05) 70%)}.fcCopy{position:relative;z-index:2;width:44%;height:100%;box-sizing:border-box;padding:0 0 0 48px;display:flex;flex-direction:column;justify-content:center}.fcK{color:#8ceafa;font-size:10px;font-weight:900;letter-spacing:3.2px}.fc h2{margin:13px 0 16px;font-size:clamp(40px,3.8vw,55px);line-height:.95;letter-spacing:-2.2px}.fc h2 span{display:block;color:#21d8f6}.fc p{max-width:470px;color:#d1e0e5;font-size:15px;line-height:1.55}.fcBtn{display:inline-flex;align-items:center;justify-content:center;gap:9px;width:max-content;margin-top:22px;padding:14px 19px;border-radius:13px;background:#21d8f6;color:#03202d;text-decoration:none;font-size:12.5px;font-weight:950}.nf{background:#02131d;color:#fff;padding:34px 0 24px}.nfS{width:min(1180px,calc(100% - 64px));margin:auto}.nfTop{display:grid;grid-template-columns:1.2fr .8fr .8fr;gap:40px;padding-bottom:27px;border-bottom:1px solid rgba(255,255,255,.08)}.nfLogo{width:140px;height:auto}.nf p{max-width:360px;color:#8faab5;font-size:12.5px;line-height:1.5}.nfCol strong{display:block;font-size:11px;letter-spacing:1.3px;margin-bottom:10px}.nfCol a{display:flex;align-items:center;gap:7px;color:#8faab5;text-decoration:none;font-size:12px;margin:8px 0}.nfBottom{display:flex;justify-content:space-between;padding-top:18px;color:#688792;font-size:11px}.nfBottom b{color:#a7bec7}
 @media(max-width:760px){.fc{padding:28px 0 24px}.fcS{width:calc(100% - 24px)}.fcPanel{height:auto;border-radius:22px}.fcVisual{position:relative;height:315px}.fcVisual img{object-position:57% center}.fcVisual:after{background:linear-gradient(180deg,rgba(3,23,34,.02) 0%,rgba(3,23,34,.12) 56%,#031722 100%)}.fcCopy{width:auto;height:auto;margin-top:-30px;padding:0 17px 23px}.fc h2{font-size:34px;letter-spacing:-1.35px}.fc p{font-size:13px;line-height:1.47}.fcBtn{width:100%;box-sizing:border-box;margin-top:17px}.nf{padding:27px 0 20px}.nfS{width:calc(100% - 30px)}.nfTop{grid-template-columns:1fr;gap:20px}.nfBottom{display:block;line-height:1.7}}
 `}</style><div className="fcS"><div className="fcPanel"><div className="fcVisual"><Image src="/naribo-ucretsiz-analiz-photo.png" alt="Naribo restoran analiz raporunu inceleyen restoran sahibi" fill sizes="(max-width:760px) 100vw, 1180px"/></div><div className="fcCopy"><div className="fcK">ÜCRETSİZ RESTORAN ANALİZİ</div><h2>NEREDEN<span>BÜYÜYEBİLİRİZ?</span></h2><p>Menünüzü, fiyatlarınızı ve dijital satışlarınızı detaylı olarak analiz ediyor, restoranınız için en büyük büyüme fırsatlarını sizinle paylaşıyoruz.</p><a className="fcBtn" href="#iletisim">Ücretsiz Analiz Talep Et <ArrowRight size={18}/></a></div></div></div></section><footer className="nf" id="iletisim"><div className="nfS"><div className="nfTop"><div><Image src="/naribo-logo.png" alt="Naribo" width={265} height={110} className="nfLogo"/><p>Restoranların dijital satışını, sipariş sayısını ve gerçek kazancını birlikte büyüten büyüme ortağı.</p></div><div className="nfCol"><strong>NARİBO</strong><a href="#hizmetler">Hizmetler</a><a href="#nasil">Nasıl Çalışıyoruz?</a><a href="#naribo-modeli">Naribo Modeli</a><a href="#analiz">Ücretsiz Analiz</a></div><div className="nfCol"><strong>İLETİŞİM</strong><a href="#iletisim"><MessageCircle size={15}/> WhatsApp</a><a href="#iletisim"><Mail size={15}/> E-posta</a><a href="#iletisim"><Instagram size={15}/> Instagram</a></div></div><div className="nfBottom"><span>© 2026 <b>Naribo</b>. Tüm hakları saklıdır.</span><span>Ajansınız değil. <b>Büyüme ortağınız.</b></span></div></div></footer></>
}
