import Image from 'next/image';
import { ArrowRight, CheckCircle2, MessageCircle } from 'lucide-react';

export default function GrowthPartnerSection(){
  return <section className="gp" id="buyume-ortaginiz"><style>{`
    .gp{background:#f3f6f7;padding:42px 0 82px}.gpS{width:min(1180px,calc(100% - 64px));margin:auto}.gpPanel{position:relative;min-height:610px;border-radius:32px;overflow:hidden;background:#031722;box-shadow:0 24px 62px rgba(8,43,58,.12)}.gpPhoto{position:absolute;inset:0}.gpPhoto img{object-fit:cover;object-position:center}.gpOverlay{position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,23,34,.92) 0%,rgba(3,23,34,.72) 38%,rgba(3,23,34,.15) 68%,rgba(3,23,34,.02) 100%)}.gpContent{position:relative;z-index:2;width:50%;padding:78px 58px;color:#fff}.gpK{color:#82e8f8;font-size:11px;font-weight:900;letter-spacing:2.8px}.gp h2{margin:15px 0 18px;font-size:clamp(45px,5vw,66px);line-height:.95;letter-spacing:-2.5px}.gp h2 span{display:block;color:#21d8f6}.gpLead{max-width:500px;color:#d0dfe4;font-size:15.5px;line-height:1.6}.gpPoints{display:flex;gap:8px;flex-wrap:wrap;margin-top:25px}.gpPoint{display:flex;align-items:center;gap:7px;padding:10px 12px;border-radius:99px;background:rgba(3,23,34,.38);border:1px solid rgba(255,255,255,.16);font-size:11.5px;font-weight:800}.gpPoint svg{color:#21d8f6}.gpCta{display:inline-flex;align-items:center;gap:9px;margin-top:27px;padding:15px 19px;border-radius:14px;background:#21d8f6;color:#03202d;text-decoration:none;font-size:13px;font-weight:950}
    @media(max-width:760px){.gp{padding:16px 0 40px}.gpS{width:calc(100% - 24px)}.gpPanel{min-height:620px;border-radius:22px}.gpPhoto img{object-position:58% center}.gpOverlay{background:linear-gradient(180deg,rgba(3,23,34,.04) 0%,rgba(3,23,34,.14) 35%,rgba(3,23,34,.94) 66%)}.gpContent{position:absolute;left:0;right:0;bottom:0;width:auto;padding:26px 19px}.gp h2{font-size:35px;letter-spacing:-1.3px}.gpLead{font-size:13.5px}.gpPoints{margin-top:16px}.gpPoint{font-size:10.5px}.gpCta{width:100%;justify-content:center;margin-top:18px}}
  `}</style><div className="gpS"><div className="gpPanel"><div className="gpPhoto"><Image src="/naribo-buyume-ortagi.png" alt="Naribo restoran buyume ortagi ile birlikte calisma" fill sizes="(max-width:760px) 100vw, 1180px"/><div className="gpOverlay"/></div><div className="gpContent"><div className="gpK">BÜYÜME ORTAĞINIZ</div><h2>SİZ MUTFAĞINIZA<span>ODAKLANIN.</span></h2><p className="gpLead">Platformların karmaşasını, kampanyaları, reklamları ve performans takibini biz yönetelim. Siz ürününüze ve müşterinize odaklanın.</p><div className="gpPoints"><div className="gpPoint"><CheckCircle2 size={16}/> Tek ekip</div><div className="gpPoint"><CheckCircle2 size={16}/> Sürekli takip</div><div className="gpPoint"><CheckCircle2 size={16}/> Sipariş + kârlılık</div></div><a className="gpCta" href="#analiz"><MessageCircle size={18}/> Restoranımı Birlikte Büyütelim <ArrowRight size={18}/></a></div></div></div></section>
}
