import Image from 'next/image';
import { ArrowRight, CheckCircle2, MessageCircle } from 'lucide-react';

export default function GrowthPartnerSection(){
  return <section className="gp" id="buyume-ortaginiz"><style>{`
    .gp{background:#f3f6f7;padding:28px 0 54px}.gpS{width:min(1320px,calc(100% - 64px));margin:auto}.gpPanel{position:relative;height:540px;border-radius:30px;overflow:hidden;background:#031722;box-shadow:0 22px 55px rgba(8,43,58,.12)}.gpPhoto{position:absolute;inset:0}.gpPhoto img{object-fit:cover;object-position:center}.gpOverlay{position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,23,34,.97) 0%,rgba(3,23,34,.88) 30%,rgba(3,23,34,.43) 48%,rgba(3,23,34,.04) 72%)}.gpContent{position:relative;z-index:2;width:43%;height:100%;box-sizing:border-box;padding-left:48px;display:flex;flex-direction:column;justify-content:center;color:#fff}.gpK{color:#82e8f8;font-size:10px;font-weight:900;letter-spacing:3.2px;margin-bottom:12px}.gp h2{margin:0;font-size:clamp(38px,3.35vw,49px);line-height:.97;letter-spacing:-1.8px}.gp h2 .gpLine{display:block;white-space:nowrap}.gp h2 .gpAccent{display:block;color:#21d8f6;margin-top:2px}.gpLead{max-width:455px;margin:15px 0 0;color:#d0dfe4;font-size:14.5px;line-height:1.48}.gpPoints{display:flex;gap:7px;flex-wrap:nowrap;margin-top:19px}.gpPoint{display:flex;align-items:center;gap:5px;padding:7px 9px;border-radius:99px;background:rgba(3,23,34,.48);border:1px solid rgba(255,255,255,.16);font-size:9.8px;font-weight:800;white-space:nowrap}.gpPoint svg{color:#21d8f6;flex:0 0 auto}.gpCta{display:inline-flex;align-items:center;gap:8px;width:max-content;margin-top:19px;padding:12px 17px;border-radius:12px;background:#21d8f6;color:#03202d;text-decoration:none;font-size:12.5px;font-weight:950}
    @media(max-width:760px){.gp{padding:14px 0 28px}.gpS{width:calc(100% - 24px)}.gpPanel{height:auto;min-height:0;border-radius:22px;background:#031722}.gpPhoto{position:relative;height:315px}.gpPhoto img{object-position:60% center}.gpOverlay{background:linear-gradient(180deg,rgba(3,23,34,.02) 0%,rgba(3,23,34,.12) 55%,#031722 100%)}.gpContent{position:relative;width:auto;height:auto;margin-top:-30px;padding:0 17px 20px;display:block;text-align:center}.gpK{font-size:11px;letter-spacing:2.4px;margin-bottom:11px}.gp h2{font-size:27px;line-height:1.02;letter-spacing:-1px}.gp h2 .gpLine{white-space:normal}.gpLead{font-size:15px;line-height:1.52;margin:13px auto 0;max-width:405px}.gpPoints{margin-top:15px;flex-wrap:wrap;justify-content:center}.gpPoint{font-size:9.8px;padding:7px 9px}.gpCta{width:100%;box-sizing:border-box;justify-content:center;margin-top:15px;padding:13px 15px}}
  `}</style><div className="gpS"><div className="gpPanel"><div className="gpPhoto"><Image src="/naribo-buyume-ortagi-photo.png" alt="PanelTakip büyüme ortağı ile restoran operasyonunu birlikte yönetme" fill sizes="(max-width:760px) 100vw, 1320px"/><div className="gpOverlay"/></div><div className="gpContent"><div className="gpK">PANELTAKİP BÜYÜME ORTAĞINIZ</div><h2><span className="gpLine">SİZ MUTFAĞINIZA</span><span className="gpAccent">ODAKLANIN.</span></h2><p className="gpLead">Restoranınızın tüm dijital süreçlerinde yanınızdayız. Panelleri biz yönetiyor, satışlarınızı birlikte büyütüyoruz.</p><div className="gpPoints"><div className="gpPoint"><CheckCircle2 size={13}/> Panel Yönetimi</div><div className="gpPoint"><CheckCircle2 size={13}/> Strateji ve Kampanyalar</div><div className="gpPoint"><CheckCircle2 size={13}/> Sürekli Destek</div></div><a className="gpCta" href="#analiz"><MessageCircle size={16}/> Büyüme Yolculuğuna Başla <ArrowRight size={16}/></a></div></div></div></section>
}
