import Image from 'next/image';
import { ArrowRight, CheckCircle2, MessageCircle } from 'lucide-react';

export default function GrowthPartnerSection(){
  return <section className="gp" id="buyume-ortaginiz"><style>{`
    .gp{background:#f3f6f7;padding:28px 0 54px}.gpS{width:min(1180px,calc(100% - 64px));margin:auto}.gpPanel{position:relative;height:540px;border-radius:30px;overflow:hidden;background:#031722;box-shadow:0 22px 55px rgba(8,43,58,.12)}.gpPhoto{position:absolute;inset:0}.gpPhoto img{object-fit:cover;object-position:center}.gpOverlay{position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,23,34,.97) 0%,rgba(3,23,34,.86) 30%,rgba(3,23,34,.42) 48%,rgba(3,23,34,.04) 72%)}.gpContent{position:relative;z-index:2;width:46%;padding:62px 0 38px 48px;color:#fff}.gpK{color:#82e8f8;font-size:10px;font-weight:900;letter-spacing:3.2px}.gp h2{margin:13px 0 15px;font-size:clamp(39px,3.6vw,52px);line-height:.96;letter-spacing:-2px}.gp h2 span{display:block;color:#21d8f6}.gpLead{max-width:470px;color:#d0dfe4;font-size:15px;line-height:1.5}.gpPoints{display:flex;gap:7px;flex-wrap:wrap;margin-top:20px}.gpPoint{display:flex;align-items:center;gap:6px;padding:8px 10px;border-radius:99px;background:rgba(3,23,34,.45);border:1px solid rgba(255,255,255,.16);font-size:10.5px;font-weight:800}.gpPoint svg{color:#21d8f6}.gpCta{display:inline-flex;align-items:center;gap:8px;margin-top:20px;padding:13px 17px;border-radius:13px;background:#21d8f6;color:#03202d;text-decoration:none;font-size:12.5px;font-weight:950}
    @media(max-width:760px){.gp{padding:14px 0 28px}.gpS{width:calc(100% - 24px)}.gpPanel{height:auto;min-height:0;border-radius:22px;background:#031722}.gpPhoto{position:relative;height:315px}.gpPhoto img{object-position:60% center}.gpOverlay{background:linear-gradient(180deg,rgba(3,23,34,.02) 0%,rgba(3,23,34,.12) 55%,#031722 100%)}.gpContent{position:relative;width:auto;margin-top:-30px;padding:0 17px 20px}.gp h2{font-size:32px;letter-spacing:-1.25px}.gpLead{font-size:13px;line-height:1.45}.gpPoints{margin-top:15px}.gpPoint{font-size:10px}.gpCta{width:100%;box-sizing:border-box;justify-content:center;margin-top:16px}}
  `}</style><div className="gpS"><div className="gpPanel"><div className="gpPhoto"><Image src="/naribo-buyume-ortagi-photo.png" alt="Naribo buyume ortagi ile restoran operasyonunu birlikte yonetme" fill sizes="(max-width:760px) 100vw, 1180px"/><div className="gpOverlay"/></div><div className="gpContent"><div className="gpK">NARİBO BÜYÜME ORTAĞINIZ</div><h2>SİZ MUTFAĞINIZA<span>ODAKLANIN.</span></h2><p className="gpLead">Restoranınızın tüm dijital süreçlerinde yanınızdayız. Panelleri biz yönetiyor, satışlarınızı birlikte büyütüyoruz.</p><div className="gpPoints"><div className="gpPoint"><CheckCircle2 size={14}/> Panel Yönetimi</div><div className="gpPoint"><CheckCircle2 size={14}/> Strateji ve Kampanyalar</div><div className="gpPoint"><CheckCircle2 size={14}/> Sürekli Destek</div></div><a className="gpCta" href="#analiz"><MessageCircle size={17}/> Büyüme Yolculuğuna Başla <ArrowRight size={17}/></a></div></div></div></section>
}
