import { BarChart3, BadgePercent, ChartNoAxesCombined, CircleDollarSign, MapPinned, QrCode, Store, UtensilsCrossed } from 'lucide-react';

const services = [
  { icon: Store, title: 'Yemek Platformu Yönetimi', text: 'Yemeksepeti, Trendyol Yemek, GetirYemek ve Migros Yemek mağazalarınızı tek noktadan yönetiyoruz.', primary:true },
  { icon: UtensilsCrossed, title: 'Menü & Fiyat Optimizasyonu', text: 'Ürün sıralaması, fiyat, açıklama, görsel ve combo yapısını satış odaklı optimize ediyoruz.', primary:true },
  { icon: CircleDollarSign, title: 'Kârlılık Yönetimi', text: 'Maliyet, komisyon, kampanya ve paketleme giderleri sonrası gerçek kazancı takip ediyoruz.', primary:true },
  { icon: BadgePercent, title: 'Kampanya Yönetimi', text: 'Doğru ürüne, doğru zamanda, kârlılığı koruyan kampanya planları oluşturuyoruz.', primary:true },
  { icon: ChartNoAxesCombined, title: 'Reklamdan Siparişe', text: 'Instagram ve Meta reklamlarından gelen müşteriyi sipariş kanalına taşıyoruz.' },
  { icon: QrCode, title: 'QR Menü', text: 'Mobil uyumlu, anlık güncellenebilen dijital menü altyapısı kuruyoruz.' },
  { icon: MapPinned, title: 'Google & Dijital İtibar', text: 'Google görünürlüğü, işletme bilgileri ve yorum süreçlerini yönetiyoruz.' },
  { icon: BarChart3, title: 'Raporlama & Büyüme Analizi', text: 'Rakamları aksiyona dönüştüren düzenli performans ve büyüme analizi sunuyoruz.' },
];

export default function NariboModelSection(){
  return <section className="svc" id="hizmetler"><style>{`
    .svc{background:#031722;color:#fff;padding:42px 0 38px;overflow:hidden}.svcShell{width:min(1320px,calc(100% - 48px));margin:auto}.svcHero{position:relative;height:570px;border-radius:30px;overflow:hidden;border:1px solid rgba(33,216,246,.16);box-shadow:0 24px 60px rgba(0,0,0,.24);background:#062838 url('/paneltakip-hizmetler-premium.png') center/cover no-repeat}.svcHero:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,23,34,.97) 0%,rgba(3,23,34,.86) 28%,rgba(3,23,34,.34) 52%,rgba(3,23,34,.02) 78%)}.svcCopy{position:relative;z-index:2;width:46%;height:100%;box-sizing:border-box;padding:58px 0 92px 62px;display:flex;flex-direction:column;justify-content:center}.svcK{display:flex;align-items:center;gap:10px;color:#8feaf8;font-size:10px;font-weight:900;letter-spacing:3px}.svcK:before{content:'';width:38px;height:1px;background:#21d8f6}.svc h2{margin:15px 0 0;font-size:clamp(48px,4.15vw,64px);line-height:.94;letter-spacing:-2.4px}.svc h2 span{display:block;color:#21d8f6}.svcLead{max-width:510px;margin:20px 0 0;color:#c3d5dc;font-size:16px;line-height:1.58}.svcGrid{position:relative;z-index:3;margin-top:-54px;padding:0 38px;display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.svcCard{min-height:132px;padding:18px;border-radius:18px;background:linear-gradient(145deg,rgba(10,55,75,.92),rgba(5,35,49,.92));backdrop-filter:blur(12px);border:1px solid rgba(33,216,246,.17);box-shadow:0 14px 30px rgba(0,0,0,.18)}.svcCard.primary{min-height:150px;background:linear-gradient(145deg,rgba(12,67,89,.97),rgba(6,42,58,.97));border-color:rgba(33,216,246,.34);box-shadow:0 18px 36px rgba(0,0,0,.23)}.svcIcon{width:40px;height:40px;border-radius:12px;display:grid;place-items:center;background:rgba(33,216,246,.10);color:#21d8f6;margin-bottom:11px}.svcCard.primary .svcIcon{width:44px;height:44px;background:rgba(33,216,246,.15)}.svcCard h3{margin:0 0 7px;font-size:14px;line-height:1.15}.svcCard.primary h3{font-size:15.5px}.svcCard p{margin:0;color:#aec3cb;font-size:11.3px;line-height:1.45}.svcPromise{margin:16px 38px 0;padding:14px 18px;border:1px solid rgba(33,216,246,.18);border-radius:14px;background:rgba(255,255,255,.045);display:flex;justify-content:center;gap:42px;font-size:13.5px;font-weight:850}.svcPromise span{color:#21d8f6}
    @media(min-width:1081px){.svc{padding:2.2vw 0 1.8vw}.svcShell{width:86vw;max-width:none}.svcHero{height:auto;aspect-ratio:2.32/1;border-radius:1.8vw}.svcCopy{padding:3.4vw 0 5vw 3.8vw}.svcK{font-size:.62vw;letter-spacing:.18vw}.svcK:before{width:2.4vw}.svc h2{font-size:3.55vw;letter-spacing:-.14vw}.svcLead{max-width:31vw;font-size:1vw;margin-top:1.2vw}.svcGrid{margin-top:-3.15vw;padding:0 2.3vw;gap:.85vw}.svcCard{min-height:8vw;padding:1.05vw;border-radius:1.1vw}.svcCard.primary{min-height:9.1vw}.svcIcon{width:2.45vw;height:2.45vw;border-radius:.7vw;margin-bottom:.65vw}.svcCard.primary .svcIcon{width:2.7vw;height:2.7vw}.svcCard h3{font-size:.87vw}.svcCard.primary h3{font-size:.96vw}.svcCard p{font-size:.7vw}.svcPromise{margin:.95vw 2.3vw 0;padding:.82vw 1vw;border-radius:.85vw;gap:2.6vw;font-size:.82vw}}
    @media(max-width:900px){.svcGrid{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:760px){.svc{padding:24px 0 28px}.svcShell{width:calc(100% - 24px)}.svcHero{height:300px;border-radius:20px;background-size:auto 300px;background-position:58% center;background-repeat:no-repeat;background-color:#031722}.svcHero:after{background:linear-gradient(180deg,rgba(3,23,34,.04) 0%,rgba(3,23,34,.12) 42%,rgba(3,23,34,.88) 72%,#031722 100%)}.svcCopy{width:100%;height:100%;padding:0 17px 17px;justify-content:flex-end;text-align:center;align-items:center}.svcK{font-size:8px;letter-spacing:1.8px}.svcK:before{display:none}.svc h2{font-size:23px;line-height:.98;letter-spacing:-.7px}.svcLead{max-width:340px;font-size:11px;line-height:1.4;margin-top:10px}.svcGrid{margin-top:10px;padding:0;grid-template-columns:1fr;gap:8px}.svcCard,.svcCard.primary{min-height:0;display:grid;grid-template-columns:46px 1fr;padding:13px;column-gap:11px}.svcIcon,.svcCard.primary .svcIcon{grid-row:1/3;margin:0;width:42px;height:42px}.svcCard h3,.svcCard.primary h3{grid-column:2;font-size:13px;margin:2px 0 4px}.svcCard p{grid-column:2;font-size:11px}.svcPromise{margin:12px 0 0;display:flex;justify-content:center;gap:5px;flex-wrap:wrap;text-align:center;line-height:1.4;font-size:11px;padding:12px 8px}.svcPromise span{display:inline}.svcPromise span:not(:last-child):after{content:' ·';color:#5f8996;margin-left:5px}}
  `}</style><div className="svcShell"><div className="svcHero"><div className="svcCopy"><div className="svcK">TÜM SÜREÇLER TEK YERDE</div><h2>RESTORANINIZIN DİJİTAL SATIŞ SİSTEMİNİ<span>BİZ YÖNETİYORUZ.</span></h2><p className="svcLead">Yemek platformlarından menünüze, fiyatlarınıza, kampanyalarınıza, reklamlarınıza ve kârlılığınıza kadar tüm dijital satış sürecini tek sistem altında yönetiyoruz.</p></div></div><div className="svcGrid">{services.map(({icon:Icon,title,text,primary})=><article className={`svcCard ${primary?'primary':''}`} key={title}><div className="svcIcon"><Icon size={21}/></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="svcPromise"><span>Panelleri yönetir.</span><span>Satışı büyütür.</span><span>Kârlılığı takip eder.</span></div></div></section>;
}
