import Image from 'next/image';
import { BarChart3, Layers3, Target } from 'lucide-react';

const pillars = [
  { icon:Target, title:'Restoranınıza özel strateji', text:'Menü, fiyat, müşteri ve platform verilerinize göre.' },
  { icon:Layers3, title:'Tek ekipten yönetim', text:'Menüden reklama kadar tek büyüme planı.' },
  { icon:BarChart3, title:'Sürekli ölçüm & gelişim', text:'Sipariş ve gerçek kazanç birlikte büyür.' },
] as const;

export default function NariboModelSection(){
  return <section className="nm" id="naribo-modeli"><style>{`
    .nm{background:#f3f6f7;padding:74px 0;color:#082b3a}.nmS{width:min(1120px,calc(100% - 64px));margin:auto}.nmK{text-align:center;color:#0c9fc2;font:900 11px/1 sans-serif;letter-spacing:2.8px}.nmH{text-align:center;margin:12px 0 12px;font-size:clamp(42px,5vw,64px);line-height:.96;letter-spacing:-2.4px}.nmH span{display:block;color:#0c9fc2}.nmP{text-align:center;max-width:700px;margin:0 auto 32px;color:#58717c;font-size:16px;line-height:1.5}.nmPanel{display:grid;grid-template-columns:1.08fr .92fr;min-height:520px;border-radius:30px;overflow:hidden;background:#041d2a;box-shadow:0 22px 55px rgba(8,43,58,.12)}.nmVisual{position:relative;min-height:520px}.nmVisual img{object-fit:cover;object-position:center}.nmShade{position:absolute;inset:0;background:linear-gradient(180deg,transparent 35%,rgba(3,23,34,.86) 100%)}.nmVisualText{position:absolute;left:28px;right:28px;bottom:26px;color:#fff}.nmVisualText small{color:#7fe8f8;font-weight:900;letter-spacing:2px}.nmVisualText h3{font-size:28px;line-height:1.02;margin:8px 0 0}.nmRight{padding:34px;display:flex;flex-direction:column;justify-content:center}.nmRightTitle{color:#fff;font-size:22px;line-height:1.1;margin:0 0 18px}.nmCards{display:grid;gap:10px}.nmCard{display:grid;grid-template-columns:48px 1fr;gap:12px;padding:15px;border:1px solid rgba(33,216,246,.15);border-radius:16px;background:#073149;color:#fff}.nmIcon{width:44px;height:44px;border-radius:13px;display:grid;place-items:center;background:rgba(33,216,246,.11);color:#21d8f6}.nmCard b{font-size:14px}.nmCard p{margin:4px 0 0;color:#bad0d8;font-size:12.5px;line-height:1.4}.nmQuote{margin-top:16px;padding:15px;border-radius:15px;background:#fff;color:#173d4c;font-size:13px;font-weight:800}
    @media(max-width:760px){.nm{padding:36px 0}.nmS{width:calc(100% - 24px)}.nmH{font-size:34px}.nmP{font-size:14px;margin-bottom:20px}.nmPanel{grid-template-columns:1fr;min-height:0;border-radius:22px}.nmVisual{min-height:360px}.nmVisualText{left:18px;right:18px;bottom:18px}.nmVisualText h3{font-size:24px}.nmRight{padding:15px}.nmRightTitle{font-size:19px;margin:2px 0 12px}.nmCard{padding:12px}.nmCard b{font-size:13px}.nmCard p{font-size:12px}.nmQuote{font-size:12.5px}}
  `}</style><div className="nmS"><div className="nmK">NARİBO MODELİ</div><h2 className="nmH">AJANSINIZ DEĞİL.<span>BÜYÜME ORTAĞINIZ.</span></h2><p className="nmP">Restoranınızın dijital satışını tek tek hizmetler olarak değil, bütün bir büyüme sistemi olarak yönetiyoruz.</p><div className="nmPanel"><div className="nmVisual"><Image src="/chef-naribo.png" alt="Naribo restoran büyüme yaklaşımı" fill sizes="(max-width:760px) 100vw, 55vw"/><div className="nmShade"/><div className="nmVisualText"><small>AYNI HEDEF</small><h3>Restoranınızın ekibine dışarıdan değil, büyümenin içinden bakıyoruz.</h3></div></div><div className="nmRight"><h3 className="nmRightTitle">Naribo'nun farkı 3 noktada.</h3><div className="nmCards">{pillars.map(({icon:Icon,title,text})=><div className="nmCard" key={title}><div className="nmIcon"><Icon size={23}/></div><div><b>{title}</b><p>{text}</p></div></div>)}</div><div className="nmQuote">Aynı masanın iki tarafı değil, aynı tarafındayız.</div></div></div></div></section>
}
