import Image from 'next/image';
import JourneyCarousel from './JourneyCarousel';
import QrMenuSection from './QrMenuSection';
import ProfitSection from './ProfitSection';
import NariboModelSection from './NariboModelSection';
import GrowthPartnerSection from './GrowthPartnerSection';
import FinalCtaSection from './FinalCtaSection';
import { ArrowRight, BarChart3, CircleCheckBig, ClipboardCheck, Clock3, Eye, Headphones, Menu, ShieldCheck, ShoppingCart, Target, TrendingUp, Users, Settings, Rocket, CircleDollarSign, RefreshCw } from 'lucide-react';

const benefits = [
  { icon: Eye, title: 'GÖRÜNÜRLÜK', text: 'Daha çok müşteriye ulaşın.' },
  { icon: Target, title: 'DÖNÜŞÜM', text: 'Görüntülenmeyi siparişe çevirin.' },
  { icon: ShoppingCart, title: 'SEPET', text: 'Sepet tutarını artırın.' },
  { icon: BarChart3, title: 'KÂRLILIK', text: 'Sipariş başı kazancı artırın.' },
];
const stats = [
  { icon: Target, title: '4 PLATFORM', text: 'Tek büyüme stratejisi' },
  { icon: TrendingUp, title: '360° ANALİZ', text: 'Menüden kârlılığa' },
  { icon: BarChart3, title: 'KÂR ODAKLI', text: 'Ciro değil, kazanç' },
  { icon: Users, title: 'RESTORANA ÖZEL', text: 'Size özel strateji' },
  { icon: Headphones, title: 'SÜREKLİ DESTEK', text: 'Sürekli yönetim ve iyileştirme' },
];
const setupSteps = [
  { no:'01',icon:ClipboardCheck,title:'ANALİZ',text:'Menü, fiyat, platform, kampanya ve mevcut dijital satış yapınızı inceliyoruz.' },
  { no:'02',icon:Target,title:'PLANLA',text:'Büyüme fırsatlarını belirleyip restoranınıza özel aksiyon planı çıkarıyoruz.' },
  { no:'03',icon:Settings,title:'YÖNET',text:'Yemek platformlarındaki günlük dijital operasyonunuzu yönetiyoruz.' },
  { no:'04',icon:Rocket,title:'BÜYÜT',text:'Menü, kampanya, reklam ve yönlendirme çalışmalarıyla satış potansiyelini büyütüyoruz.' },
  { no:'05',icon:CircleDollarSign,title:'KÂRI ÖLÇ',text:'Komisyon ve maliyet sonrası restoranınıza kalan gerçek kazancı izliyoruz.' },
  { no:'06',icon:RefreshCw,title:'İYİLEŞTİR',text:'Sonuçları ölçüp bir sonraki büyüme aksiyonunu planlıyoruz.' },
];
const platformLogos=[
  {src:'/platforms/ymksptpng-v2.png',alt:'Yemeksepeti'},
  {src:'/platforms/ubrpng-v2.png',alt:'Trendyol Yemek'},
  {src:'/platforms/gtrpng-v2.png',alt:'Getir Yemek'},
  {src:'/platforms/mgrspng-v2.png',alt:'Migros Yemek'},
];
function PlatformLogoRow({mobile=false}:{mobile?:boolean}){return <div className={mobile?'platformLogoRow platformLogoRowMobile':'platformLogoRow'}>{platformLogos.map(p=><img key={p.src} src={p.src} alt={p.alt}/>)}</div>}
function Logo(){return <a className="brand" href="#" aria-label="PanelTakip ana sayfa"><Image src="/paneltakip-logo-transparent.png" alt="PanelTakip" width={265} height={110} priority className="brandImage"/></a>}

export default function Home(){return <main><style>{`
.mobilePlatformBand{display:none}.platformLogoRow{display:flex;align-items:center;justify-content:center;gap:42px;width:100%;height:100%}.platformLogoRow img{display:block;width:auto;height:76px;object-fit:contain}.setupSection{padding:56px 0 54px!important;background:#f2f5f6!important}.setupIntro{display:block!important;text-align:center!important;margin-bottom:30px!important}.setupIntro>div{max-width:900px;margin:0 auto}.setupIntro>p{max-width:720px!important;margin:14px auto 0!important;font-size:14px!important;line-height:1.5!important}.setupIntro .sectionKicker{justify-content:center!important}.setupIntro .sectionKicker:after{content:'';width:42px;height:2px;background:var(--blue)}.setupIntro h2{font-size:clamp(36px,3.5vw,50px)!important;line-height:.98!important;letter-spacing:-2px!important}.setupIntro h2 span{color:#0c9fc2!important}.setupFlow{position:relative!important;display:grid!important;grid-template-columns:repeat(6,1fr)!important;gap:0!important;padding:0 4px!important}.setupFlow:before{content:''!important;position:absolute!important;left:7%;right:7%;top:34px!important;height:2px!important;background:#18c7e7!important;opacity:.28!important}.setupCard{min-height:190px!important;padding:0 13px 8px!important;background:transparent!important;border:0!important;text-align:center!important}.setupTop{display:block!important;margin:0 auto 14px!important;position:relative!important;height:70px!important}.setupIcon{position:absolute!important;left:50%!important;top:0!important;transform:translateX(-50%)!important;width:68px!important;height:68px!important;border-radius:50%!important;color:#0aa7c9!important;background:#fff!important;border:1px solid #cdebf1!important;box-shadow:0 8px 22px rgba(8,72,94,.07)!important}.setupNo{position:absolute!important;z-index:3!important;top:-7px!important;left:calc(50% + 20px)!important;display:grid!important;place-items:center!important;width:27px!important;height:27px!important;border-radius:50%!important;background:#07374a!important;color:#7ce5f4!important;font-size:9px!important;font-weight:900!important;border:3px solid #f2f5f6!important}.setupCard h3{min-height:28px!important;margin:0 0 7px!important;font-size:13px!important;color:#073246!important;font-weight:900!important}.setupCard p{max-width:165px!important;margin:0 auto!important;color:#657d87!important;font-size:11.5px!important;line-height:1.42!important}.setupFoot{margin-top:8px!important;min-height:54px!important;border-radius:15px!important;padding:12px 20px!important;background:#082f40!important}.setupPlatforms{gap:9px!important}.setupPlatforms span{color:#65dff2!important}.setupResult{font-weight:700!important}.approvedJourney{background:#031722;padding:20px 0}.approvedJourneyDesktop{position:relative;width:min(1320px,calc(100% - 64px));height:430px;margin:auto;overflow:hidden;border-radius:30px}.approvedJourneyDesktop img{width:100%;height:100%;object-fit:cover}.approvedJourneyMobile{display:none}
@media(max-width:760px){.hero{padding-bottom:0!important}.heroGrid{width:100%!important;max-width:none!important;margin:0!important;padding-left:28px!important;padding-right:28px!important}.benefitStack{order:3!important;padding:28px 0 20px!important;gap:12px!important}.benefitCard{min-height:104px!important;padding:18px 16px!important;background:linear-gradient(145deg,#07395a,#062d47)!important;border:1px solid rgba(33,216,246,.28)!important;border-radius:22px!important}.mobilePlatformBand{order:4;display:flex!important;width:calc(100% + 56px);height:92px;margin:0 -28px;background:#fff;align-items:center;justify-content:center;overflow:hidden;border-radius:0 0 26px 26px}.platformLogoRowMobile{gap:14px;padding:8px 18px}.platformLogoRowMobile img{height:62px;max-width:22%;object-fit:contain}.platformWrap,.stats{display:none!important}.setupSection{padding:36px 0 34px!important}.setupIntro{width:calc(100% - 36px)!important;margin-bottom:22px!important}.setupIntro h2{font-size:28px!important;line-height:1!important;letter-spacing:-1.1px!important}.setupIntro>p{font-size:12.5px!important}.setupFlow{width:calc(100% - 36px)!important;display:grid!important;grid-template-columns:1fr!important;gap:8px!important;padding:0!important}.setupFlow:before{display:none!important}.setupCard{min-height:0!important;display:grid!important;grid-template-columns:62px 1fr!important;column-gap:12px!important;text-align:left!important;padding:11px 12px 11px 4px!important;background:#fff!important;border:1px solid #e0eaed!important;border-radius:15px!important}.setupTop{grid-row:1/3!important;grid-column:1!important;width:62px!important;height:56px!important;margin:0!important}.setupIcon{width:52px!important;height:52px!important;left:26px!important;top:2px!important}.setupNo{top:-4px!important;left:40px!important;width:23px!important;height:23px!important;font-size:8px!important;border-color:#fff!important}.setupCard h3{grid-column:2!important;min-height:0!important;margin:2px 0 4px!important;font-size:12.5px!important}.setupCard p{grid-column:2!important;max-width:none!important;margin:0!important;font-size:11.2px!important}.setupFoot{width:calc(100% - 36px)!important;margin-top:12px!important;padding:13px!important;display:block!important;text-align:center!important}.setupPlatforms{justify-content:center!important;font-size:10.5px!important}.setupResult{justify-content:center!important;margin-top:9px!important;font-size:11px!important}.approvedJourney{padding:0}.approvedJourneyDesktop{display:none}.approvedJourneyMobile{display:block}}
`}</style>
<section className="hero"><div className="heroGlow"/><header className="nav shell"><Logo/><nav className="desktopNav" aria-label="Ana menü"><a href="#">Ana Sayfa</a><a href="#hizmetler">Hizmetler</a><a href="#nasil">Nasıl Çalışıyoruz?</a><a href="#basari">Kârlılık</a><a href="#iletisim">İletişim</a></nav><a className="contactButton" href="#analiz">Ücretsiz Analiz <ArrowRight size={18}/></a><button className="mobileMenu" aria-label="Menüyü aç"><Menu/></button></header><div className="growthBand"><span/>RESTORANLARIN BÜYÜME ORTAĞI<span/></div><div className="heroGrid shell"><div className="heroVisual"><div className="chefPlaceholder" style={{backgroundImage:"url('/chef-naribo.png')"}}/></div><div className="heroCopy"><div className="eyebrow"><span/> PANELTAKİP · RESTORAN BÜYÜME & YÖNETİM</div><h1><span>DAHA FAZLA</span><br/><strong>SİPARİŞ.</strong><br/><em>DAHA KÂRLI<br/>BÜYÜME.</em></h1><p>Restoranınızın yemek platformlarından reklama, menü yönetiminden kârlılığa kadar dijital satış sistemini yönetiyoruz.</p><div className="heroActionDock"><a className="primaryCta" href="#analiz">Ücretsiz Restoran Analizi <ArrowRight size={20}/></a><div className="microTrust"><span><TrendingUp size={16}/> Hızlı analiz</span><span><Clock3 size={16}/> Size özel strateji</span><span><ShieldCheck size={16}/> Ücretsiz danışmanlık</span></div></div></div><div className="benefitStack">{benefits.map(({icon:Icon,title,text})=><article className="benefitCard" key={title}><Icon size={32}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="mobilePlatformBand"><PlatformLogoRow mobile/></div></div></section>
<section className="platformWrap shell"><div className="platformImageBar"><PlatformLogoRow/></div></section><section className="stats shell">{stats.map(({icon:Icon,title,text})=><article className="stat" key={title}><Icon size={34}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</section>
<NariboModelSection/>
<section className="setupSection" id="nasil"><div className="shell setupIntro"><div><div className="sectionKicker">NASIL ÇALIŞIYORUZ?</div><h2>ANALİZDEN AKSİYONA <span>6 ADIMDA</span><br/>SÜREKLİ BÜYÜME.</h2></div><p>Analiz ediyor, planlıyor, yönetiyor, büyütüyor, gerçek kazancı ölçüyor ve sürekli iyileştiriyoruz.</p></div><div className="shell setupFlow">{setupSteps.map(({no,icon:Icon,title,text})=><article className="setupCard" key={no}><div className="setupTop"><div className="setupIcon"><Icon size={25}/></div><div className="setupNo">{no}</div></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="shell setupFoot"><div className="setupPlatforms"><span>TEK AKIŞ</span><strong>ANALİZ</strong><i>→</i><strong>PLANLA</strong><i>→</i><strong>YÖNET</strong><i>→</i><strong>BÜYÜT</strong><i>→</i><strong>KÂRI ÖLÇ</strong><i>→</i><strong>İYİLEŞTİR</strong></div><div className="setupResult"><CircleCheckBig size={20}/> Sürekli yönetim, sürekli optimizasyon.</div></div></section>
<section className="approvedJourney"><div className="approvedJourneyDesktop"><Image src="/reklamdan-siparise.png" alt="PanelTakip reklamdan siparişe yönlendirme sistemi" width={1672} height={941}/></div><div className="approvedJourneyMobile"><JourneyCarousel/></div></section>
<QrMenuSection/><ProfitSection/><GrowthPartnerSection/><FinalCtaSection/>
</main>;}
