import Image from 'next/image';
import JourneyCarousel from './JourneyCarousel';
import QrMenuSection from './QrMenuSection';
import ProfitSection from './ProfitSection';
import NariboModelSection from './NariboModelSection';
import GrowthPartnerSection from './GrowthPartnerSection';
import FinalCtaSection from './FinalCtaSection';
import { ArrowRight, BarChart3, CircleCheckBig, ClipboardCheck, Clock3, Eye, Headphones, Menu, ShieldCheck, ShoppingCart, Target, TrendingUp, Users, Settings, Rocket, CircleDollarSign, RefreshCw } from 'lucide-react';

const benefits=[{icon:Eye,title:'GÖRÜNÜRLÜK',text:'Daha çok müşteriye ulaşın.'},{icon:Target,title:'DÖNÜŞÜM',text:'Görüntülenmeyi siparişe çevirin.'},{icon:ShoppingCart,title:'SEPET',text:'Sepet tutarını artırın.'},{icon:BarChart3,title:'KÂRLILIK',text:'Sipariş başı kazancı artırın.'}];
const stats=[{icon:Target,title:'4 PLATFORM',text:'Tek büyüme stratejisi'},{icon:TrendingUp,title:'360° ANALİZ',text:'Menüden kârlılığa'},{icon:BarChart3,title:'KÂR ODAKLI',text:'Ciro değil, kazanç'},{icon:Users,title:'RESTORANA ÖZEL',text:'Size özel strateji'},{icon:Headphones,title:'SÜREKLİ DESTEK',text:'Sürekli yönetim ve iyileştirme'}];
const setupSteps=[{no:'01',icon:ClipboardCheck,title:'ANALİZ',text:'Menü, fiyat, platform ve mevcut satış yapınızı inceliyoruz.'},{no:'02',icon:Target,title:'PLANLA',text:'Restoranınıza özel büyüme fırsatlarını ve aksiyon planını çıkarıyoruz.'},{no:'03',icon:Settings,title:'YÖNET',text:'Platform, menü, fiyat ve kampanya operasyonunu yönetiyoruz.'},{no:'04',icon:Rocket,title:'BÜYÜT',text:'Reklam, kampanya ve yönlendirmelerle satış potansiyelini büyütüyoruz.'},{no:'05',icon:CircleDollarSign,title:'KÂRI ÖLÇ',text:'Komisyon ve maliyet sonrası gerçek kazancı ölçüyoruz.'},{no:'06',icon:RefreshCw,title:'İYİLEŞTİR',text:'Sonuçları analiz edip bir sonraki büyüme aksiyonunu uyguluyoruz.'}];
const platformLogos=[{src:'/platforms/ymksptpng-v2.png',alt:'Yemeksepeti'},{src:'/platforms/ubrpng-v2.png',alt:'Trendyol Yemek'},{src:'/platforms/gtrpng-v2.png',alt:'Getir Yemek'},{src:'/platforms/mgrspng-v2.png',alt:'Migros Yemek'}];
function PlatformLogoRow({mobile=false}:{mobile?:boolean}){return <div className={mobile?'platformLogoRow platformLogoRowMobile':'platformLogoRow'}>{platformLogos.map(p=><img key={p.src} src={p.src} alt={p.alt}/>)}</div>}
function Logo(){return <a className="brand" href="#" aria-label="PanelTakip ana sayfa"><Image src="/paneltakip-logo-transparent.png" alt="PanelTakip" width={265} height={110} priority className="brandImage"/></a>}

export default function Home(){return <main><style>{`
.mobilePlatformBand{display:none}.platformLogoRow{display:flex;align-items:center;justify-content:center;gap:42px;width:100%;height:100%}.platformLogoRow img{display:block;width:auto;height:76px;object-fit:contain}.processPremium{background:#031722;padding:4px 0 22px;color:#fff}.processShell{width:min(1320px,calc(100% - 48px));margin:auto}.processPanel{position:relative;min-height:600px;border-radius:30px;overflow:hidden;background:#062838 url('/paneltakip-nasil-calisiyoruz-premium.png') 30% center/cover no-repeat;border:1px solid rgba(33,216,246,.16);box-shadow:0 24px 60px rgba(0,0,0,.24)}.processPanel:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,23,34,0) 0%,rgba(3,23,34,.05) 27%,rgba(3,23,34,.62) 44%,rgba(3,23,34,.94) 100%)}.processContent{position:relative;z-index:2;width:72%;margin-left:auto;padding:72px 44px 36px 24px;box-sizing:border-box}.processK{display:flex;align-items:center;justify-content:center;gap:10px;color:#8feaf8;font-size:10px;font-weight:900;letter-spacing:3px}.processK:before,.processK:after{content:'';width:40px;height:1px;background:#21d8f6}.processContent h2{text-align:center;margin:12px auto 0;max-width:850px;font-size:clamp(34px,2.75vw,43px);line-height:.97;letter-spacing:-1.4px}.processContent h2 span{color:#21d8f6}.processLead{text-align:center;margin:14px auto 28px;max-width:720px;color:#c4d6dd;font-size:15px;line-height:1.5}.processFlow{position:relative;display:grid;grid-template-columns:repeat(6,1fr);gap:12px}.processFlow:before{content:'';position:absolute;left:5%;right:5%;top:40px;height:1px;background:rgba(33,216,246,.52)}.processStep{position:relative;text-align:center}.processTop{position:relative;height:84px}.processIcon{position:absolute;z-index:2;left:50%;top:0;transform:translateX(-50%);width:76px;height:76px;border-radius:50%;display:grid;place-items:center;background:#082f40;border:1px solid #21d8f6;color:#21d8f6;box-shadow:0 8px 20px rgba(0,0,0,.18)}.processNo{position:absolute;z-index:3;left:calc(50% + 22px);top:-7px;width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:#21d8f6;color:#03202d;font-size:8px;font-weight:950;border:3px solid #062838}.processStep h3{margin:7px 0 7px;font-size:13px}.processStep p{margin:0 auto;max-width:145px;color:#b8cbd2;font-size:11.5px;line-height:1.48}.processFoot{margin:34px auto 0;max-width:820px;padding:15px 22px;border-radius:14px;background:rgba(33,216,246,.09);border:1px solid rgba(33,216,246,.2);display:flex;align-items:center;justify-content:center;gap:9px;color:#e2f0f4;font-size:13px;font-weight:750}.approvedJourney{background:#031722;padding:2px 0 16px}.approvedJourneyDesktop{position:relative;width:min(1320px,calc(100% - 64px));height:430px;margin:auto;overflow:hidden;border-radius:30px}.approvedJourneyDesktop img{width:100%;height:100%;object-fit:cover}.approvedJourneyMobile{display:none}
@media(max-width:760px){.hero{padding-bottom:0!important}.heroGrid{width:100%!important;max-width:none!important;margin:0!important;padding-left:28px!important;padding-right:28px!important}.benefitStack{order:3!important;padding:28px 0 20px!important;gap:12px!important}.benefitCard{min-height:104px!important;padding:18px 16px!important;background:linear-gradient(145deg,#07395a,#062d47)!important;border:1px solid rgba(33,216,246,.28)!important;border-radius:22px!important}.mobilePlatformBand{order:4;display:flex!important;width:calc(100% + 56px);height:92px;margin:0 -28px;background:#fff;align-items:center;justify-content:center;overflow:hidden;border-radius:0 0 26px 26px}.platformLogoRowMobile{gap:14px;padding:8px 18px}.platformLogoRowMobile img{height:62px;max-width:22%;object-fit:contain}.platformWrap,.stats{display:none!important}.processPremium{padding:6px 0 16px}.processShell{width:calc(100% - 24px)}.processPanel{min-height:0;padding-top:330px;border-radius:22px;background-position:28% center}.processPanel:after{background:linear-gradient(180deg,rgba(3,23,34,0) 0%,rgba(3,23,34,.08) 35%,#031722 59%,#031722 100%)}.processContent{width:100%;padding:10px 14px 20px}.processK{font-size:9px;letter-spacing:2px}.processK:before,.processK:after{width:22px}.processContent h2{font-size:25px;line-height:1}.processLead{font-size:12.5px;margin-bottom:18px}.processFlow{grid-template-columns:1fr;gap:8px}.processFlow:before{display:none}.processStep{display:grid;grid-template-columns:60px 1fr;text-align:left;padding:11px;border-radius:13px;background:rgba(255,255,255,.045);border:1px solid rgba(33,216,246,.1)}.processTop{grid-row:1/3;width:56px;height:56px}.processIcon{width:52px;height:52px;left:26px}.processNo{left:38px;width:22px;height:22px}.processStep h3{grid-column:2;margin:3px 0 4px;font-size:12.5px}.processStep p{grid-column:2;max-width:none;margin:0;font-size:11px}.processFoot{margin-top:14px;font-size:11px;text-align:center}.approvedJourney{padding:0}.approvedJourneyDesktop{display:none}.approvedJourneyMobile{display:block}}
`}</style>
<section className="hero"><div className="heroGlow"/><header className="nav shell"><Logo/><nav className="desktopNav" aria-label="Ana menü"><a href="#">Ana Sayfa</a><a href="#hizmetler">Hizmetler</a><a href="#nasil">Nasıl Çalışıyoruz?</a><a href="#basari">Kârlılık</a><a href="#iletisim">İletişim</a></nav><a className="contactButton" href="#analiz">Ücretsiz Analiz <ArrowRight size={18}/></a><button className="mobileMenu" aria-label="Menüyü aç"><Menu/></button></header><div className="growthBand"><span/>RESTORANLARIN BÜYÜME ORTAĞI<span/></div><div className="heroGrid shell"><div className="heroVisual"><div className="chefPlaceholder" style={{backgroundImage:"url('/chef-paneltakip.png')"}}/></div><div className="heroCopy"><div className="eyebrow"><span/> PANELTAKİP · RESTORAN BÜYÜME & YÖNETİM</div><h1><span>DAHA FAZLA</span><br/><strong>SİPARİŞ.</strong><br/><em>DAHA KÂRLI<br/>BÜYÜME.</em></h1><p>Restoranınızın yemek platformlarından reklama, menü yönetiminden kârlılığa kadar dijital satış sistemini yönetiyoruz.</p><div className="heroActionDock"><a className="primaryCta" href="#analiz">Ücretsiz Restoran Analizi <ArrowRight size={20}/></a><div className="microTrust"><span><TrendingUp size={16}/> Hızlı analiz</span><span><Clock3 size={16}/> Size özel strateji</span><span><ShieldCheck size={16}/> Ücretsiz danışmanlık</span></div></div></div><div className="benefitStack">{benefits.map(({icon:Icon,title,text})=><article className="benefitCard" key={title}><Icon size={32}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="mobilePlatformBand"><PlatformLogoRow mobile/></div></div></section>
<section className="platformWrap shell"><div className="platformImageBar"><PlatformLogoRow/></div></section><section className="stats shell">{stats.map(({icon:Icon,title,text})=><article className="stat" key={title}><Icon size={34}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</section>
<NariboModelSection/>
<section className="processPremium" id="nasil"><div className="processShell"><div className="processPanel"><div className="processContent"><div className="processK">NASIL ÇALIŞIYORUZ?</div><h2>ANALİZDEN AKSİYONA <span>6 ADIMDA</span><br/>SÜREKLİ BÜYÜME.</h2><p className="processLead">Restoranınıza özel strateji ile başlıyor, ölçülebilir sonuçlarla büyümenizi sağlıyoruz.</p><div className="processFlow">{setupSteps.map(({no,icon:Icon,title,text})=><article className="processStep" key={no}><div className="processTop"><div className="processIcon"><Icon size={25}/></div><div className="processNo">{no}</div></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="processFoot"><CircleCheckBig size={18}/> Panelleri yönetiyor, sonuçları ölçüyor ve sürekli iyileştiriyoruz.</div></div></div></div></section>
<section className="approvedJourney"><div className="approvedJourneyDesktop"><Image src="/reklamdan-siparise.png" alt="PanelTakip reklamdan siparişe yönlendirme sistemi" width={1672} height={941}/></div><div className="approvedJourneyMobile"><JourneyCarousel/></div></section>
<QrMenuSection/><ProfitSection/><GrowthPartnerSection/><FinalCtaSection/>
</main>;}
