'use client';

import { useState } from 'react';
import { ArrowLeft, ArrowRight, BadgePercent, CircleCheckBig, Image as ImageIcon, MenuSquare, QrCode, Smartphone, Sparkles } from 'lucide-react';

const slides = [
  {
    key: 'qr',
    label: 'MASADA QR',
    title: 'QR kodu okutun.',
    text: 'Müşteriniz masadaki QR kodu okutur; menünüz saniyeler içinde telefonda açılır.',
  },
  {
    key: 'phone',
    label: 'DİJİTAL MENÜ',
    title: 'Menü telefonda yaşasın.',
    text: 'Kategori, ürün, açıklama, görsel ve fiyatlar mobil uyumlu tek menüde sunulur.',
  },
  {
    key: 'panel',
    label: 'YÖNETİM PANELİ',
    title: 'Fiyatı siz değiştirin.',
    text: 'Ürünleri, fiyatları, görselleri ve kampanya alanlarını panelden anında güncelleyin.',
  },
] as const;

export default function QrMenuSection(){
  const [active,setActive]=useState(0);
  const prev=()=>setActive((active-1+slides.length)%slides.length);
  const next=()=>setActive((active+1)%slides.length);
  const s=slides[active];

  return <section className="qrS" id="qr-menu"><style>{`
    .qrS{background:#031722;color:#fff;padding:64px 0 70px;overflow:hidden}.qrShell{width:min(1180px,calc(100% - 64px));margin:auto}.qrHead{text-align:center;max-width:860px;margin:0 auto 34px}.qrK{display:flex;align-items:center;justify-content:center;gap:10px;color:#86e8f8;font-size:10px;font-weight:900;letter-spacing:3px}.qrK:before,.qrK:after{content:'';width:38px;height:1px;background:#21d8f6}.qrHead h2{margin:13px 0 12px;font-size:clamp(40px,4vw,56px);line-height:.96;letter-spacing:-2px}.qrHead h2 span{color:#21d8f6}.qrHead p{max-width:700px;margin:auto;color:#b9cbd3;font-size:15px;line-height:1.55}
    .qrPanel{display:grid;grid-template-columns:.9fr 1.1fr;min-height:520px;border:1px solid rgba(33,216,246,.17);border-radius:30px;overflow:hidden;background:linear-gradient(145deg,#062b3d,#031722);box-shadow:0 22px 60px rgba(0,0,0,.2)}.qrCopy{padding:50px 42px;display:flex;flex-direction:column;justify-content:center}.qrSlideTag{color:#7ee7f7;font-size:10px;font-weight:900;letter-spacing:2.4px}.qrCopy h3{margin:10px 0 13px;font-size:38px;line-height:.98;letter-spacing:-1.6px}.qrCopy p{margin:0;color:#c2d4dc;font-size:14.5px;line-height:1.55;max-width:430px}.qrFeatures{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:24px}.qrFeature{display:flex;align-items:center;gap:9px;padding:12px 13px;border-radius:14px;background:#083348;border:1px solid rgba(33,216,246,.12);font-size:11.5px;font-weight:750}.qrFeature svg{color:#25d8f5;flex:0 0 auto}.qrCta{display:inline-flex;align-items:center;gap:9px;width:max-content;margin-top:23px;padding:13px 17px;border-radius:12px;background:#21d8f6;color:#03202d;font-size:12.5px;font-weight:950}
    .qrStage{position:relative;min-height:520px;background:radial-gradient(circle at 65% 40%,rgba(27,211,241,.14),transparent 28%),linear-gradient(135deg,#041d2b,#082f41)}.qrScene{position:absolute;inset:0;display:grid;place-items:center;padding:38px}.qrVisual{position:relative;width:100%;height:100%;min-height:430px;border-radius:24px;overflow:hidden;border:1px solid rgba(255,255,255,.08);background:linear-gradient(145deg,#0a3143,#061d2b)}
    .qrTable{position:absolute;inset:0;background:radial-gradient(circle at 70% 22%,rgba(255,182,92,.16),transparent 22%),linear-gradient(180deg,#102d38 0%,#0b2531 55%,#3a261d 56%,#291b17 100%)}.qrStand{position:absolute;left:18%;top:20%;width:150px;height:230px;border-radius:16px;background:#f3efe7;color:#071d28;box-shadow:0 24px 44px rgba(0,0,0,.35);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;transform:perspective(600px) rotateY(-7deg)}.qrStand strong{font-size:18px}.qrCodeFake{width:86px;height:86px;background:repeating-conic-gradient(#081b24 0 25%,#fff 0 50%) 0/18px 18px;border:8px solid #fff;box-shadow:0 0 0 1px #ccd2d4}.qrPlate{position:absolute;right:8%;bottom:10%;width:270px;height:145px;border-radius:50%;background:radial-gradient(circle at 52% 48%,#d55f2b 0 10%,#c9934d 11% 20%,#263139 21% 48%,#111 49% 100%);box-shadow:0 18px 30px rgba(0,0,0,.38)}
    .phoneWrap{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:250px;height:430px;border-radius:38px;padding:10px;background:linear-gradient(145deg,#394951,#071116 45%,#2e3c43);box-shadow:0 30px 60px rgba(0,0,0,.42)}.phoneScreen{height:100%;border-radius:30px;overflow:hidden;background:#f8fbfc;color:#102b39}.phoneTop{height:68px;background:#062b3c;color:#fff;padding:17px 15px 0;font-weight:900;text-align:center}.phoneCats{display:flex;gap:6px;padding:10px;overflow:hidden}.phoneCats span{padding:6px 8px;border-radius:999px;background:#e8f7fa;font-size:8px;white-space:nowrap}.phoneCats span:first-child{background:#23d3ef;color:#053042}.foodCard{margin:8px 10px;padding:9px;border-radius:12px;background:#fff;box-shadow:0 4px 12px rgba(8,45,62,.08);display:grid;grid-template-columns:58px 1fr auto;gap:9px;align-items:center}.foodPic{width:58px;height:48px;border-radius:9px;background:radial-gradient(circle at 55% 45%,#d96a2d 0 14%,#9f5c31 15% 35%,#263238 36% 100%)}.foodCard strong{display:block;font-size:10px}.foodCard small{font-size:8px;color:#7c9098}.foodPrice{font-size:10px;font-weight:900}.plus{width:24px;height:24px;border-radius:50%;background:#062b3c;color:#fff;display:grid;place-items:center;font-size:14px}
    .laptop{position:absolute;left:50%;top:51%;transform:translate(-50%,-50%);width:480px;height:300px;border-radius:18px;background:#111a1f;padding:10px;box-shadow:0 28px 55px rgba(0,0,0,.42)}.lapScreen{height:100%;border-radius:10px;background:#f5f8fa;color:#12313f;overflow:hidden;display:grid;grid-template-columns:110px 1fr}.side{background:#062b3c;color:#fff;padding:20px 12px}.side b{display:block;margin-bottom:20px}.side span{display:block;font-size:9px;padding:7px 0;color:#b6d0d8}.dash{padding:19px}.dashTop{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.dashTop strong{font-size:16px}.dashTop button{border:0;background:#22d4ef;color:#04232f;border-radius:9px;padding:8px 10px;font-size:9px;font-weight:800}.row{display:grid;grid-template-columns:46px 1fr 58px 52px;gap:10px;align-items:center;padding:9px;border-radius:10px;background:#fff;margin:7px 0;box-shadow:0 3px 10px rgba(0,0,0,.05);font-size:9px}.thumb{width:46px;height:34px;border-radius:7px;background:radial-gradient(circle,#cf7b38,#25343a)}.status{color:#15945e;font-weight:900}
    .qrNav{position:absolute;z-index:5;top:50%;transform:translateY(-50%);width:44px;height:44px;border-radius:50%;border:1px solid rgba(33,216,246,.42);background:rgba(3,23,34,.85);color:#21d8f6;display:grid;place-items:center}.qrPrev{left:14px}.qrNext{right:14px}.qrDots{position:absolute;z-index:6;left:50%;bottom:16px;transform:translateX(-50%);display:flex;gap:7px}.qrDots button{border:0;width:7px;height:7px;border-radius:99px;background:#426575;padding:0}.qrDots button.active{width:24px;background:#21d8f6}
    @media(max-width:760px){.qrS{padding:42px 0}.qrShell{width:calc(100% - 24px)}.qrHead{margin-bottom:23px;padding:0 8px}.qrHead h2{font-size:31px;letter-spacing:-1.2px}.qrHead p{font-size:13px}.qrPanel{grid-template-columns:1fr;min-height:0;border-radius:22px}.qrCopy{padding:25px 18px 20px;order:2}.qrCopy h3{font-size:29px}.qrCopy p{font-size:12.8px}.qrFeatures{grid-template-columns:1fr;gap:8px;margin-top:17px}.qrCta{width:100%;justify-content:center;box-sizing:border-box}.qrStage{min-height:390px;order:1}.qrScene{padding:16px}.qrVisual{min-height:350px}.qrStand{left:10%;top:17%;width:120px;height:190px}.qrPlate{width:190px;height:105px}.phoneWrap{width:205px;height:350px}.laptop{width:310px;height:210px}.lapScreen{grid-template-columns:78px 1fr}.row{grid-template-columns:36px 1fr 44px 42px;gap:6px;padding:6px}.thumb{width:36px;height:28px}.qrNav{width:38px;height:38px}.qrPrev{left:7px}.qrNext{right:7px}}
  `}</style>
  <div className="qrShell"><div className="qrHead"><div className="qrK">NARİBO QR MENÜ</div><h2>MASADAN TELEFONA.<br/><span>MENÜNÜZ ARTIK DİJİTAL.</span></h2><p>QR menünüzü kuruyor, mobil deneyimini tasarlıyor ve ürün-fiyat güncellemelerini kolayca yönetebileceğiniz bir sistem sunuyoruz.</p></div>
  <div className="qrPanel"><div className="qrCopy"><div className="qrSlideTag">{s.label}</div><h3>{s.title}</h3><p>{s.text}</p><div className="qrFeatures"><div className="qrFeature"><Smartphone size={17}/> Mobil uyumlu</div><div className="qrFeature"><BadgePercent size={17}/> Anlık fiyat güncelleme</div><div className="qrFeature"><ImageIcon size={17}/> Görsel & kategori yönetimi</div><div className="qrFeature"><Sparkles size={17}/> Naribo tasarım dili</div></div><a className="qrCta" href="#analiz">QR Menü Çözümünü İncele <ArrowRight size={16}/></a></div>
  <div className="qrStage"><div className="qrScene"><div className="qrVisual">{s.key==='qr'&&<div className="qrTable"><div className="qrStand"><strong>naribo</strong><div className="qrCodeFake"/><span style={{fontSize:11,fontWeight:800}}>MENÜ İÇİN OKUTUN</span></div><div className="qrPlate"/></div>}{s.key==='phone'&&<div className="phoneWrap"><div className="phoneScreen"><div className="phoneTop">naribo<br/><span style={{fontSize:9,fontWeight:500}}>DİJİTAL MENÜ</span></div><div className="phoneCats"><span>Tümü</span><span>Başlangıçlar</span><span>Ana Yemekler</span></div>{['Izgara Dana Bonfile','Trüflü Makarna','Cheeseburger','Künefe'].map((x,i)=><div className="foodCard" key={x}><div className="foodPic"/><div><strong>{x}</strong><small>Özenle hazırlanır</small></div><div><div className="foodPrice">₺{[420,320,280,180][i]}</div><div className="plus">+</div></div></div>)}</div></div>}{s.key==='panel'&&<div className="laptop"><div className="lapScreen"><div className="side"><b>naribo</b><span>Ana Sayfa</span><span>Menü</span><span>Kampanyalar</span><span>Görseller</span><span>QR Menü</span></div><div className="dash"><div className="dashTop"><strong>Menü Yönetimi</strong><button>+ Ürün Ekle</button></div>{['Izgara Dana Bonfile','Trüflü Makarna','Cheeseburger','Humus'].map((x,i)=><div className="row" key={x}><div className="thumb"/><b>{x}</b><strong>₺{[420,320,280,180][i]}</strong><span className="status">Aktif</span></div>)}</div></div></div>}</div></div><button className="qrNav qrPrev" onClick={prev} aria-label="Önceki"><ArrowLeft size={20}/></button><button className="qrNav qrNext" onClick={next} aria-label="Sonraki"><ArrowRight size={20}/></button><div className="qrDots">{slides.map((x,i)=><button key={x.key} className={i===active?'active':''} onClick={()=>setActive(i)} aria-label={`${i+1}. görsel`}/>)}</div></div></div></div></section>
}
