import Image from 'next/image';
import { ArrowRight, BadgePercent, Image as ImageIcon, QrCode, Smartphone } from 'lucide-react';

export default function QrMenuSection(){
  return <section className="qrS" id="qr-menu"><style>{`
    .qrS{background:#031722;color:#fff;padding:64px 0 70px;overflow:hidden}.qrShell{width:min(1180px,calc(100% - 64px));margin:auto}.qrPanel{display:grid;grid-template-columns:.92fr 1.08fr;grid-template-areas:'copy stage' 'actions stage';min-height:510px;border:1px solid rgba(33,216,246,.17);border-radius:30px;overflow:hidden;background:linear-gradient(145deg,#062b3d,#031722);box-shadow:0 22px 60px rgba(0,0,0,.2)}.qrCopy{grid-area:copy;padding:54px 46px 18px;display:flex;flex-direction:column;justify-content:flex-end}.qrK{display:flex;align-items:center;gap:10px;color:#86e8f8;font-size:10px;font-weight:900;letter-spacing:3px}.qrK:before{content:'';width:38px;height:1px;background:#21d8f6}.qrCopy h2{margin:15px 0 16px;font-size:clamp(39px,3.8vw,54px);line-height:.96;letter-spacing:-2px}.qrCopy h2 span{color:#21d8f6}.qrCopy>p{margin:0;color:#c2d4dc;font-size:15px;line-height:1.58;max-width:455px}.qrActions{grid-area:actions;padding:0 46px 50px}.qrFeatures{display:flex;flex-wrap:wrap;gap:8px;margin-top:22px}.qrFeature{display:flex;align-items:center;gap:7px;padding:10px 11px;border-radius:12px;background:#083348;border:1px solid rgba(33,216,246,.12);font-size:11px;font-weight:800}.qrFeature svg{color:#25d8f5}.qrCta{display:inline-flex;align-items:center;gap:9px;width:max-content;margin-top:22px;padding:14px 18px;border-radius:12px;background:#21d8f6;color:#03202d;font-size:12.5px;font-weight:950;text-decoration:none}.qrStage{grid-area:stage;position:relative;min-height:510px;overflow:hidden;background:#071d29}.qrStage:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(3,23,34,.22),transparent 34%);pointer-events:none}.qrPhoto{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center center}
    @media(max-width:760px){.qrS{padding:38px 0 42px}.qrShell{width:calc(100% - 24px)}.qrPanel{grid-template-columns:1fr;grid-template-areas:'copy' 'stage' 'actions';min-height:0;border-radius:22px}.qrCopy{padding:27px 19px 22px;justify-content:flex-start}.qrK{font-size:9px}.qrCopy h2{font-size:31px;letter-spacing:-1.2px;margin:12px 0 13px}.qrCopy>p{font-size:12.8px}.qrStage{min-height:355px}.qrActions{padding:18px 19px 25px}.qrFeatures{display:grid;grid-template-columns:1fr;gap:8px;margin-top:0}.qrFeature{width:100%;box-sizing:border-box;font-size:10.5px;padding:11px 12px}.qrCta{width:100%;justify-content:center;box-sizing:border-box;margin-top:16px}.qrPhoto{object-position:center center}}
  `}</style><div className="qrShell"><div className="qrPanel"><div className="qrCopy"><div className="qrK">NARİBO QR MENÜ</div><h2>MASADAN TELEFONA.<br/><span>MENÜNÜZ ARTIK DİJİTAL.</span></h2><p>Basılı menülere bağlı kalmayın. Müşteriniz QR kodu okutsun; güncel menünüze, ürünlerinize ve fiyatlarınıza saniyeler içinde ulaşsın.</p></div><div className="qrStage"><Image src="/naribo-qr-menu.png" alt="Naribo QR Menü restoran masası ve mobil dijital menü" fill sizes="(max-width:760px) 100vw, 55vw" className="qrPhoto" /></div><div className="qrActions"><div className="qrFeatures"><div className="qrFeature"><QrCode size={16}/> QR ile anında erişim</div><div className="qrFeature"><Smartphone size={16}/> Mobil uyumlu menü</div><div className="qrFeature"><BadgePercent size={16}/> Anlık fiyat güncelleme</div><div className="qrFeature"><ImageIcon size={16}/> Ürün & görsel yönetimi</div></div><a className="qrCta" href="/qr-menu">QR Menü'yü İncele <ArrowRight size={16}/></a></div></div></div></section>;
}
