import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, BadgePercent, Image as ImageIcon, QrCode, Smartphone } from 'lucide-react';

const features=[
  [QrCode,'QR ile anında erişim','Müşteriniz masadaki QR kodu okutarak menünüze saniyeler içinde ulaşır.'],
  [Smartphone,'Mobil uyumlu dijital menü','Kategori, ürün, açıklama, görsel ve fiyatlar telefonda temiz ve hızlı görüntülenir.'],
  [BadgePercent,'Anlık fiyat güncelleme','Fiyat değişikliklerinde yeniden baskı gerekmez; dijital menünüz güncel kalır.'],
  [ImageIcon,'Ürün ve görsel yönetimi','Ürünlerinizi, açıklamalarınızı ve görsellerinizi tek dijital menü yapısında yönetirsiniz.']
] as const;

export default function QrMenuPage(){return <main className="qrd"><style>{`
.qrd{min-height:100vh;background:#031722;color:#fff}.qrdTop{width:min(1180px,calc(100% - 48px));margin:auto;padding:24px 0}.qrdBack{display:inline-flex;align-items:center;gap:7px;color:#bcd3dc;text-decoration:none;font-size:12px}.qrdHero{width:min(1180px,calc(100% - 48px));margin:auto;display:grid;grid-template-columns:.9fr 1.1fr;align-items:center;gap:46px;padding:34px 0 64px}.qrdK{color:#8feaf8;font-size:11px;font-weight:800;letter-spacing:3.5px}.qrd h1{margin:14px 0 16px;font-size:clamp(44px,5vw,70px);line-height:.94;letter-spacing:-2.5px}.qrd h1 span{color:#21d8f6}.qrdLead{max-width:520px;color:#c4d7df;font-size:16px;line-height:1.6}.qrdCta{display:inline-flex;align-items:center;gap:9px;margin-top:22px;padding:14px 18px;border-radius:12px;background:#21d8f6;color:#03202d;text-decoration:none;font-size:13px;font-weight:900}.qrdPhoto{position:relative;height:590px;border-radius:28px;overflow:hidden;border:1px solid rgba(33,216,246,.18)}.qrdPhoto img{object-fit:cover}.qrdFeatures{background:#f2f5f6;color:#092838;padding:70px 0}.qrdFeatureShell{width:min(1120px,calc(100% - 48px));margin:auto}.qrdFeatureHead{text-align:center;max-width:760px;margin:0 auto 34px}.qrdFeatureHead small{color:#0c9fc2;font-size:11px;font-weight:900;letter-spacing:3px}.qrdFeatureHead h2{margin:12px 0;font-size:48px;line-height:.98}.qrdFeatureHead p{color:#607680;line-height:1.55}.qrdGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.qrdCard{padding:24px;border-radius:20px;background:#fff;border:1px solid #dfeaec}.qrdIcon{width:44px;height:44px;border-radius:13px;display:grid;place-items:center;background:#e7fafd;color:#0aa7c9}.qrdCard h3{font-size:16px;margin:18px 0 8px}.qrdCard p{margin:0;color:#607680;font-size:13px;line-height:1.5}.qrdNote{max-width:850px;margin:30px auto 0;padding:18px 20px;border-radius:16px;background:#082f40;color:#d6e8ed;text-align:center;font-size:13px}.qrdNote strong{color:#21d8f6}
@media(max-width:760px){.qrdTop{width:calc(100% - 28px);padding:18px 0}.qrdHero{width:calc(100% - 24px);grid-template-columns:1fr;gap:22px;padding:22px 0 34px;text-align:center}.qrdK{font-size:10px;letter-spacing:4px}.qrd h1{font-size:34px;line-height:.96;letter-spacing:-1.3px}.qrdLead{font-size:13px;line-height:1.55;margin-left:auto;margin-right:auto}.qrdCta{width:100%;box-sizing:border-box;justify-content:center}.qrdPhoto{height:420px;border-radius:22px;order:-1}.qrdFeatures{padding:42px 0}.qrdFeatureShell{width:calc(100% - 24px)}.qrdFeatureHead h2{font-size:29px;line-height:.98}.qrdFeatureHead p{font-size:12px}.qrdGrid{grid-template-columns:1fr;gap:9px}.qrdCard{display:grid;grid-template-columns:46px 1fr;column-gap:12px;padding:16px}.qrdIcon{grid-row:1/3}.qrdCard h3{margin:2px 0 4px;font-size:14px}.qrdCard p{font-size:12px}.qrdNote{font-size:12px}}
`}</style><div className="qrdTop"><Link href="/" className="qrdBack"><ArrowLeft size={15}/> Naribo ana sayfa</Link></div><section className="qrdHero"><div><div className="qrdK">NARİBO QR MENÜ</div><h1>MENÜNÜZ<br/><span>ARTIK DİJİTAL.</span></h1><p className="qrdLead">Basılı menülere bağlı kalmadan ürünlerinizi, görsellerinizi ve fiyatlarınızı güncel tutun. Müşteriniz QR kodu okutsun ve menünüze telefonundan anında ulaşsın.</p><a className="qrdCta" href="#ozellikler">QR Menü Özellikleri <ArrowRight size={16}/></a></div><div className="qrdPhoto"><Image src="/naribo-qr-menu.png" alt="Naribo QR Menü" fill priority sizes="(max-width:760px) 100vw, 55vw"/></div></section><section className="qrdFeatures" id="ozellikler"><div className="qrdFeatureShell"><div className="qrdFeatureHead"><small>QR MENÜ SİSTEMİ</small><h2>MENÜ YÖNETİMİNİ KOLAYLAŞTIRIN.</h2><p>Menünüzü dijital ortamda güncel tutun; müşterilerinize hızlı, modern ve mobil uyumlu bir menü deneyimi sunun.</p></div><div className="qrdGrid">{features.map(([Icon,title,text])=><article className="qrdCard" key={title}><div className="qrdIcon"><Icon size={22}/></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="qrdNote"><strong>QR Menü yalnızca dijital menü hizmetidir.</strong> Masadan sipariş ve sipariş otomasyonu Naribo'nun ayrı bir hizmeti olarak geliştirilecektir.</div></div></section></main>}
