'use client';

import '../../qr-menu/admin/premium-v2.css';
import './typography.css';
import './sections.css';
import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import {Activity,AlertCircle,BarChart3,Bell,ChevronDown,ChevronLeft,Edit3,Eye,GripVertical,Home,ImageOff,LayoutGrid,Menu,MessageSquareText,MoreHorizontal,MoreVertical,Plus,QrCode,Search,Settings,Star,Store,Tags,Trash2,Utensils,Wifi,MapPin,Phone,Instagram,CheckCircle2,Clock,ExternalLink,Save} from 'lucide-react';

type Category={id:string;name:string;isActive:boolean;sortOrder:number};
type Product={id:string;categoryId:string;name:string;description:string;price:number;image:string;allergens?:string[];isActive:boolean;sortOrder:number};
type Restaurant={id:string;slug:string;name:string;logo:string;cover:string;description:string;phone:string;address:string;instagram:string;wifiName:string;wifiPassword:string;iban:string;directionsUrl:string;openingHours:Record<string,string>;themeColor:string};
type Call={id:string;tableNo:string;note:string;status:string;createdAt:string;resolvedAt?:string};
type Feedback={id:string;rating:number;comment:string;customerName:string;createdAt:string};
type Stats={todayViews:number;totalViews:number;averageRating:number;feedbackCount:number;pendingCalls:number;dailyViews:{day:string;count:number}[];topProducts:{id:string;name:string;image:string;price:number;views:number}[]};
type Data={restaurant:Restaurant;categories:Category[];products:Product[];calls:Call[];feedback:Feedback[];stats:Stats};
type Tab='overview'|'menu'|'categories'|'qr'|'restaurant'|'calls'|'feedback'|'stats'|'settings';
const PREVIEW_DATA:Data={restaurant:{id:'preview',slug:'makarilla',name:'Makarilla',logo:'',cover:'',description:'İyi malzeme. İyi tarif. İyi lezzet.',phone:'0532 429 02 90',address:'Karşıyaka, İzmir',instagram:'makarilla',wifiName:'Makarilla',wifiPassword:'',iban:'',directionsUrl:'',openingHours:{Pazartesi:'11:00 - 23:00',Salı:'11:00 - 23:00',Çarşamba:'11:00 - 23:00',Perşembe:'11:00 - 23:00',Cuma:'11:00 - 23:30',Cumartesi:'11:00 - 23:30',Pazar:'11:00 - 23:00'},themeColor:'#14b8c4'},categories:[{id:'c1',name:'Makarnalar',isActive:true,sortOrder:1},{id:'c2',name:'Wraplar',isActive:true,sortOrder:2},{id:'c3',name:'Salatalar',isActive:true,sortOrder:3},{id:'c4',name:'Tatlılar',isActive:true,sortOrder:4}],products:[{id:'p1',categoryId:'c1',name:'Bolonez Makarna',description:'Özel bolonez sos ile',price:299,image:'/makarilla_tabak.png',allergens:[],isActive:true,sortOrder:1},{id:'p2',categoryId:'c1',name:'Alfredo Makarna',description:'Kremalı alfredo sos',price:289,image:'/makarilla_tabak.png',allergens:[],isActive:true,sortOrder:2},{id:'p3',categoryId:'c2',name:'Tavuk Wrap',description:'Izgara tavuk ve özel sos',price:239,image:'/wrap_banner.png',allergens:[],isActive:true,sortOrder:3}],calls:[],feedback:[{id:'f1',rating:5,comment:'Lezzet harikaydı, tekrar geleceğim.',customerName:'Misafir',createdAt:'2026-09-16T19:20:00.000Z'},{id:'f2',rating:5,comment:'Servis çok hızlıydı.',customerName:'Misafir',createdAt:'2026-09-14T18:10:00.000Z'},{id:'f3',rating:4,comment:'Makarna biraz daha sıcak olabilirdi.',customerName:'Misafir',createdAt:'2026-09-12T20:05:00.000Z'}],stats:{todayViews:28,totalViews:468,averageRating:4.8,feedbackCount:12,pendingCalls:0,dailyViews:[{day:'Pzt',count:18},{day:'Sal',count:22},{day:'Çar',count:17},{day:'Per',count:28},{day:'Cum',count:25},{day:'Cmt',count:31},{day:'Paz',count:24}],topProducts:[{id:'p1',name:'Bolonez Makarna',image:'/makarilla_tabak.png',price:299,views:124},{id:'p2',name:'Alfredo Makarna',image:'/makarilla_tabak.png',price:289,views:98},{id:'p3',name:'Tavuk Wrap',image:'/wrap_banner.png',price:239,views:76}]}};


export default function Page(){
 const params=useParams<{restaurant:string}>(),slug=String(params.restaurant||'').toLowerCase();
 const[data,setData]=useState<Data|null>(PREVIEW_DATA),[loading,setLoading]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[tab,setTab]=useState<Tab>('overview'),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[editing,setEditing]=useState<Product|null>(null),[isNew,setIsNew]=useState(false);
 const load=async(silent=false)=>{setData(PREVIEW_DATA);setError('');setLoading(false)};
 useEffect(()=>{},[slug]);
 useEffect(()=>{},[slug]);
 const action=async(body:any)=>true;
 const products=data?.products||[],categories=data?.categories||[],filtered=useMemo(()=>products.filter(p=>(category==='all'||p.categoryId===category)&&(!query||`${p.name} ${p.description}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR')))),[products,category,query]);
 const persist=async(next:Product[])=>{if(data)setData({...data,products:next})};
 if(loading)return <main className="qrAdminPremium"><div style={{padding:40}}>Panel yükleniyor...</div></main>;
 if(error||!data)return <main className="qrAdminPremium"><div style={{padding:40}}><h1>{error}</h1></div></main>;
 const nav:[Tab,string,any][]=[['overview','Genel Bakış',Home],['menu','Menüm',Utensils],['categories','Kategoriler',Tags],['qr','QR Kod',QrCode],['restaurant','Restoran Bilgileri',Store],['calls','Garson Çağrıları',Bell],['feedback','Geri Bildirimler',Star],['stats','İstatistikler',BarChart3],['settings','Ayarlar',Settings]];
 const openNew=()=>{setEditing({id:`new-${Date.now()}`,categoryId:category==='all'?(categories[0]?.id||''):category,name:'',description:'',price:0,image:'',allergens:[],isActive:true,sortOrder:products.length+1});setIsNew(true)};
 return <main className="qrAdminPremium ptShell">
  <aside className="ptSidebar">
    <button className="ptBrand" onClick={()=>setTab('overview')}><span><b>Panel</b><strong>Takip</strong></span><small>Restoranların Büyüme Ortağı</small></button>
    <nav className="ptNav">{nav.map(([id,label,I])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={18}/><span>{label}</span>{id==='calls'&&data.stats.pendingCalls>0&&<em>{data.stats.pendingCalls}</em>}</button>)}</nav>
    <div className="ptGrowCard"><div className="ptBars">▂ ▅ ▇</div><b>Menünüz dijitalde.<br/>Kontrol sizde.</b><i/></div>
    <div className="ptVersion"><b>PanelTakip.com</b><span>QR Menü</span></div>
  </aside>

  <section className={`ptWorkspace ${tab==="overview"?"ptWorkspaceOverview":""}`}>
    <header className="ptTopbar">
      <button className="ptMobileMenu"><Menu size={18}/></button>
      <label className="ptSearch"><Search size={18}/><input placeholder="Menü, ürün veya kategori ara..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></label>
      <div className="ptDateCard"><span>18 Eylül 2026</span><b>QR Menü Yönetimi</b></div>
      <button className="ptRestaurant"><Store size={18}/><span><b>{data.restaurant.name}</b><small>Karşıyaka, İzmir</small></span><ChevronDown size={15}/></button>
      <button className="ptIconBtn ptNotification" onClick={()=>setTab('calls')}><Bell size={18}/>{data.stats.pendingCalls>0&&<i>{data.stats.pendingCalls}</i>}</button>
      <button className="ptProfile"><span>MA</span><div><b>Makarilla</b><small>Yönetici</small></div><ChevronDown size={15}/></button>
    </header>
<div className="ptContent">
      <section className="qaMain ptAdminSurface">
       {tab==='overview'&&<Overview data={data} setTab={setTab} resolve={id=>action({action:'resolveCall',id})}/>} 
       {tab==='menu'&&<div className="qaPage qaMenuPage"><Title title="Menüm" sub="Ürünleri, fiyatları ve görünürlüğü yönetin." action={<button className="qaAdd" onClick={openNew}><Plus size={15}/>Ürün Ekle</button>}/><div className="qaMenuToolbar"><label className="qaSearch"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün ara..."/></label><div className="qaCategoryChips"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>Tümü</button>{categories.map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div></div><div className="qaProductList qaProductTable">{filtered.map(p=><div className="qaProductRow" key={p.id} onClick={()=>{setEditing(p);setIsNew(false)}}><img src={p.image||'/makarilla_tabak.png'} alt=""/><div className="qaProductInfo"><b>{p.name}</b><small>{categories.find(c=>c.id===p.categoryId)?.name} · {p.isActive?'Yayında':'Pasif'}</small></div><strong className="qaProductPrice">₺{p.price}</strong><button className={p.isActive?'qaToggle on':'qaToggle'} onClick={e=>{e.stopPropagation();void persist(products.map(x=>x.id===p.id?{...x,isActive:!x.isActive}:x))}}><i/></button><button className="qaRowMore" onClick={e=>e.stopPropagation()}><MoreVertical size={18}/></button></div>)}</div></div>}
       {tab==='categories'&&<Categories cats={categories} products={products} save={c=>action({action:'saveCategory',category:c})} del={id=>action({action:'deleteCategory',id})}/>} 
       {tab==='qr'&&<QrSection restaurant={data.restaurant}/>} 
       {tab==='restaurant'&&<RestaurantSection restaurant={data.restaurant} save={r=>action({action:'updateRestaurant',restaurant:r})}/>} 
       {tab==='calls'&&<CallsSection calls={data.calls} resolve={id=>action({action:'resolveCall',id})}/>} 
       {tab==='feedback'&&<FeedbackSection items={data.feedback} stats={data.stats}/>} 
       {tab==='stats'&&<StatsSection stats={data.stats}/>} 
       {tab==='settings'&&<SettingsSection restaurant={data.restaurant} save={r=>action({action:'updateRestaurant',restaurant:r})}/>} 
      </section>
    </div>
  </section>

  {editing&&<Editor p={editing} cats={categories} isNew={isNew} close={()=>{setEditing(null);setIsNew(false)}} save={async p=>{setEditing(null);setIsNew(false);await persist(isNew?[...products,p]:products.map(x=>x.id===p.id?p:x))}} del={async id=>{if(confirm('Bu ürünü silmek istiyor musunuz?')){setEditing(null);await persist(products.filter(x=>x.id!==id))}}}/>} 
 </main>
}

function Title({title,sub,action}:{title:string;sub:string;action?:React.ReactNode}){return <div className="qaTitleRow"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Overview({data,setTab,resolve}:{data:Data;setTab:(t:Tab)=>void;resolve:(id:string)=>void}){
 const{products,categories,stats}=data;
 const active=products.filter(p=>p.isActive).length;
 const missingImages=products.filter(p=>!p.image?.trim()).length;
 const missingDescriptions=products.filter(p=>!p.description?.trim()).length;
 const healthIssues=missingImages+missingDescriptions+products.filter(p=>!p.isActive).length;
 const healthScore=products.length?Math.max(0,100-Math.round((healthIssues/(products.length*3))*100)):0;
 const pending=data.calls.filter(c=>c.status==='pending').slice(0,3);
 const top=stats.topProducts.length?stats.topProducts:products.slice(0,3).map(p=>({id:p.id,name:p.name,image:p.image,price:p.price,views:0}));
 return <div className="qaPage qaOverviewDashboard qaOverviewCompact">
  <div className="qaOverviewTop">
   <Metric icon={<Eye size={18}/>} value={String(stats.todayViews)} label="QR Görüntüleme" note="Bugün"/>
   <Metric icon={<Utensils size={18}/>} value={String(products.length)} label="Menü Ürünü" note={`${active} aktif`}/>
   <Metric icon={<Star size={18}/>} value={stats.feedbackCount?stats.averageRating.toFixed(1):"—"} label="Müşteri Puanı" note={`${stats.feedbackCount} geri bildirim`}/>
   <Metric icon={<Bell size={18}/>} value={String(stats.pendingCalls)} label="Bekleyen Çağrı" note={stats.pendingCalls?"Yanıt bekliyor":"Aktif çağrı yok"}/>
   <button className="qaPrimaryAction" onClick={()=>setTab("menu")}><Plus size={18}/><span>Ürün Ekle</span></button>
  </div>
  <div className="qaOverviewMainGrid">
   <section className="qaDashCard qaPerformanceCard"><div className="qaDashHead"><div><h2>Menü Performansı</h2></div><span className="qaStatusPill">Son 7 gün</span></div><MiniChart rows={stats.dailyViews}/></section>
   <section className="qaDashCard qaHealthCard"><div className="qaDashHead"><div><h2>Menü Sağlığı</h2></div></div><div className="qaHealthCompact"><div className="qaHealthRing"><strong>{healthScore}%</strong></div><div className="qaHealthList"><div><CheckCircle2/><span><b>{active}/{products.length}</b> ürün yayında</span></div><div><CheckCircle2/><span>{missingImages?`${missingImages} görsel eksik`:"Görsel var"}</span></div><div><CheckCircle2/><span>{missingDescriptions?`${missingDescriptions} açıklama eksik`:"Açıklama var"}</span></div></div></div></section>
   <section className="qaDashCard qaQuickCompact"><div className="qaDashHead"><div><h2>Hızlı İşlemler</h2></div></div><div className="qaQuickGrid qaQuickGridCompact"><Quick icon={<Plus/>} title="Ürün Düzenle" sub="" on={()=>setTab("menu")}/><Quick icon={<Tags/>} title="Kategorileri Yönet" sub="" on={()=>setTab("categories")}/><Quick icon={<QrCode/>} title="QR Kod" sub="" on={()=>setTab("qr")}/><Quick icon={<Store/>} title="Restoran Bilgileri" sub="" on={()=>setTab("restaurant")}/></div></section>
  </div>
  <div className="qaOverviewBottomGrid">
   <section className="qaDashCard"><div className="qaDashHead"><div><h2>Öne Çıkan Ürünler</h2></div><button onClick={()=>setTab("menu")}>Tümünü Gör</button></div><div className="qaPopularList qaPopularTable">{top.slice(0,3).map((p,i)=><div key={p.id}><span className="qaRank">{i+1}</span><img src={p.image||"/makarilla_tabak.png"} alt=""/><div><b>{p.name}</b><small>{p.views} görüntülenme</small></div><strong>₺{p.price}</strong></div>)}</div></section>
   <section className="qaDashCard"><div className="qaDashHead"><div><h2>Son Geri Bildirimler</h2></div><button onClick={()=>setTab("feedback")}>Tümünü Gör</button></div>{data.feedback.length?<div className="qaFeedbackMini">{data.feedback.slice(0,3).map(f=><div key={f.id}><b>{"★".repeat(f.rating)}{"☆".repeat(5-f.rating)}</b><span>{f.comment||"Yorum bırakılmadı."}</span></div>)}</div>:<div className="qaCompactEmpty"><MessageSquareText size={18}/><span>Henüz geri bildirim yok.</span></div>}</section>
   <section className="qaDashCard"><div className="qaDashHead"><div><h2>Garson Çağrıları</h2></div><button onClick={()=>setTab("calls")}>Tümünü Gör</button></div>{pending.length?<div className="qaCallMini">{pending.map(c=><div key={c.id}><b>Masa {c.tableNo}</b><small>{ago(c.createdAt)}</small><button onClick={()=>resolve(c.id)}>Tamamlandı</button></div>)}</div>:<div className="qaCompactEmpty qaCompactCall"><Bell size={24}/><span>Aktif garson çağrısı yok.</span></div>}</section>
  </div>
 </div>
}
function Metric({icon,value,label,note}:{icon:React.ReactNode;value:string;label:string;note:string}){return <div className="qaMetric qaDashboardMetric"><i>{icon}</i><strong>{value}</strong><span>{label}</span><small>{note}</small></div>}
function Quick({icon,title,sub,on}:{icon:React.ReactNode;title:string;sub:string;on:()=>void}){return <button onClick={on}>{icon}<span><b>{title}</b><small>{sub}</small></span></button>}
function Empty({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="qaEmptyState">{icon}<b>{title}</b><span>{text}</span></div>}
function MiniChart({rows}:{rows:{day:string;count:number}[]}){const labels=["Cmt","Paz","Pzt","Sal","Çar","Per","Cum"];const days=labels.map((day,i)=>({day,count:rows.find(x=>x.day===day)?.count||rows[i]?.count||0})),max=Math.max(1,...days.map(x=>x.count));return <div className="qaRealChart">{days.map(d=><div key={d.day}><span style={{height:`${Math.max(8,(d.count/max)*100)}%`}} title={`${d.count} görüntülenme`}></span><b>{d.count}</b><small>{d.day}</small></div>)}</div>}
function Categories({cats,products,save,del}:{cats:Category[];products:Product[];save:(c:any)=>void;del:(id:string)=>void}){const[editing,setEditing]=useState<Category|null>(null);return <div className="qaPage qaCategoriesPage"><Title title="Kategoriler" sub="Kategorileri düzenleyin ve menü sırasını yönetin." action={<button className="qaAdd" onClick={()=>setEditing({id:'',name:'',isActive:true,sortOrder:cats.length+1})}><Plus/>Kategori Ekle</button>}/><div className="qaCategoryCards">{cats.map(x=>{const sample=products.find(p=>p.categoryId===x.id),count=products.filter(p=>p.categoryId===x.id).length;return <article key={x.id}><div className="qaCategoryDrag"><GripVertical/></div><img src={sample?.image||'/makarilla_tabak.png'} alt=""/><div><b>{x.name}</b><small>{count} ürün · {x.isActive?'Aktif':'Pasif'}</small></div><button onClick={()=>setEditing(x)}><Edit3/></button></article>})}</div>{editing&&<div className="qaInlineEditor"><h3>{editing.id?'Kategori Düzenle':'Yeni Kategori'}</h3><input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="Kategori adı"/><label><input type="checkbox" checked={editing.isActive} onChange={e=>setEditing({...editing,isActive:e.target.checked})}/> Menüde aktif</label><div><button onClick={()=>setEditing(null)}>Vazgeç</button>{editing.id&&<button className="danger" onClick={()=>{void del(editing.id);setEditing(null)}}>Sil</button>}<button className="primary" onClick={()=>{void save(editing);setEditing(null)}}>Kaydet</button></div></div>}</div>}
function QrSection({restaurant}:{restaurant:Restaurant}){const url=`https://makarilla.menu.paneltakip.com/menu/${restaurant.slug}`;return <div className="qaPage qaQrPage"><Title title="QR Kod" sub="Müşterilerin menünüze ulaşacağı QR kodu ve canlı bağlantı."/><div className="qaQrLayout"><section className="qaManageCard qaQrCard"><div className="qaQrVisual"><QrCode size={100}/></div><div><h2>{restaurant.name} QR Menü</h2><p>Masa üstü kartlar ve basılı materyaller için hazır.</p></div></section><section className="qaManageCard qaQrActions"><h2>Menü Bağlantısı</h2><label>Canlı adres<input readOnly value={url}/></label><div className="qaQrButtons"><button className="qaSecondary" onClick={()=>navigator.clipboard.writeText(url)}>Bağlantıyı Kopyala</button><a href={url} target="_blank" rel="noreferrer"><ExternalLink/>Menüyü Aç</a><button className="qaSecondary"><QrCode/>QR İndir</button></div><div className="qaInfo"><b>Öneri</b><span>Masa üstü QR kartlarında restorana özel bu adresi kullanın.</span></div></section></div></div>}
function RestaurantSection({restaurant,save}:{restaurant:Restaurant;save:(r:Restaurant)=>void}){const[d,setD]=useState(restaurant);return <div className="qaPage qaRestaurantPage"><Title title="Restoran Bilgileri" sub="İşletme, iletişim ve menü görünüm bilgilerini yönetin." action={<button className="qaAdd" onClick={()=>save(d)}><Save/>Kaydet</button>}/><div className="qaRestaurantGrid"><section className="qaManageCard"><h2>Restoran Profili</h2><Field label="Restoran Adı" value={d.name} set={v=>setD({...d,name:v})}/><Field label="Kısa Açıklama" value={d.description} set={v=>setD({...d,description:v})}/><div className="qaUploadGrid"><div className="qaUploadBox"><b>Restoran Logosu</b><span>JPG, PNG veya WEBP</span><button>Fotoğraf Yükle</button></div><div className="qaUploadBox"><b>Kapak Görseli</b><span>JPG, PNG veya WEBP</span><button>Fotoğraf Yükle</button></div></div></section><section className="qaManageCard"><h2>İletişim & Konum</h2><Field label="Telefon" value={d.phone} set={v=>setD({...d,phone:v})}/><Field label="Adres" value={d.address} set={v=>setD({...d,address:v})}/><Field label="Instagram" value={d.instagram} set={v=>setD({...d,instagram:v})}/><Field label="Yol Tarifi URL" value={d.directionsUrl} set={v=>setD({...d,directionsUrl:v})}/></section><section className="qaManageCard"><h2>Müşteri Kolaylıkları</h2><Field label="Wi-Fi Adı" value={d.wifiName} set={v=>setD({...d,wifiName:v})}/><Field label="Wi-Fi Şifresi" value={d.wifiPassword} set={v=>setD({...d,wifiPassword:v})}/><Field label="IBAN" value={d.iban} set={v=>setD({...d,iban:v})}/><label>Tema Rengi<div className="qaColorRow"><input type="color" value={d.themeColor||'#14b8c4'} onChange={e=>setD({...d,themeColor:e.target.value})}/><span>{d.themeColor||'#14b8c4'}</span></div></label></section></div></div>}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label>{label}<input value={value||''} onChange={e=>set(e.target.value)}/></label>}
function CallsSection({calls,resolve}:{calls:Call[];resolve:(id:string)=>void}){const pending=calls.filter(c=>c.status==='pending').length,done=calls.length-pending;return <div className="qaPage qaCallsPage"><Title title="Garson Çağrıları" sub="Müşteri çağrılarını canlı takip edin ve tamamlayın."/><div className="qaCallMetrics"><Metric icon={<Bell/>} value={String(pending)} label="Bekleyen" note="Aktif çağrı"/><Metric icon={<CheckCircle2/>} value={String(done)} label="Bugün Tamamlanan" note="Çözülen çağrı"/><Metric icon={<Clock/>} value={pending?'2 dk':'—'} label="Ortalama Yanıt" note="Bugünkü süre"/></div><section className="qaManageCard qaCallsCard"><div className="qaDashHead"><div><h2>Çağrı Akışı</h2><p>Yeni çağrılar en üstte görünür.</p></div></div><div className="qaCallList">{calls.length?calls.map(x=><div key={x.id} className={x.status==='pending'?'pending':''}><i><Bell/></i><div><b>Masa {x.tableNo}</b><span>{x.note||'Garson çağrısı'}</span><small>{new Date(x.createdAt).toLocaleString('tr-TR')}</small></div><strong>{x.status==='pending'?'Bekliyor':'Tamamlandı'}</strong>{x.status==='pending'&&<button onClick={()=>resolve(x.id)}><CheckCircle2/>Tamamlandı</button>}</div>):<div className="qaLargeEmpty"><Bell/><b>Şu anda bekleyen çağrı yok</b><span>Müşteri çağrı yaptığında burada görünecek.</span></div>}</div></section></div>}
function FeedbackSection({items,stats}:{items:Feedback[];stats:Stats}){const positive=items.length?Math.round(items.filter(x=>x.rating>=4).length/items.length*100):0,dist=[5,4,3,2,1].map(r=>({rating:r,count:items.filter(x=>x.rating===r).length})),max=Math.max(1,...dist.map(x=>x.count));return <div className="qaPage qaFeedbackPage"><Title title="Geri Bildirimler" sub="Müşteri puanlarını ve yorumlarını tek ekrandan takip edin."/><div className="qaFeedbackMetrics"><Metric icon={<Star/>} value={stats.feedbackCount?stats.averageRating.toFixed(1):'—'} label="Ortalama Puan" note={`${stats.feedbackCount} değerlendirme`}/><Metric icon={<MessageSquareText/>} value={String(stats.feedbackCount)} label="Toplam Yorum" note="Müşteri geri bildirimi"/><Metric icon={<CheckCircle2/>} value={`${positive}%`} label="Olumlu" note="4 ve 5 yıldız"/></div><div className="qaFeedbackGrid"><section className="qaManageCard"><div className="qaDashHead"><div><h2>Puan Dağılımı</h2><p>Son değerlendirmelerin dağılımı.</p></div></div><div className="qaRatingBars">{dist.map(x=><div key={x.rating}><span>{x.rating} yıldız</span><i><b style={{width:`${(x.count/max)*100}%`}}/></i><strong>{x.count}</strong></div>)}</div></section><section className="qaManageCard"><div className="qaDashHead"><div><h2>Son Yorumlar</h2><p>En yeni müşteri deneyimleri.</p></div></div><div className="qaFeedbackList">{items.length?items.slice(0,5).map(f=><article key={f.id}><div><b>{f.customerName}</b><span>{'★'.repeat(f.rating)}{'☆'.repeat(5-f.rating)}</span></div><p>{f.comment||'Yorum bırakılmadı.'}</p><small>{new Date(f.createdAt).toLocaleDateString('tr-TR')}</small></article>):<Empty icon={<MessageSquareText/>} title="Henüz geri bildirim yok" text="Müşteriler değerlendirme yaptığında burada görünecek."/>}</div></section></div></div>}
function StatsSection({stats}:{stats:Stats}){const peak=stats.dailyViews.length?Math.max(...stats.dailyViews.map(x=>x.count)):0;return <div className="qaPage qaStatsPage"><Title title="İstatistikler" sub="QR menünüzün kullanım ve ürün performansını takip edin."/><div className="qaStatsMetrics"><Metric icon={<Eye/>} value={String(stats.todayViews)} label="Bugün" note="Menü görüntülenmesi"/><Metric icon={<BarChart3/>} value={String(stats.totalViews)} label="Toplam" note="Menü görüntülenmesi"/><Metric icon={<Star/>} value={stats.feedbackCount?stats.averageRating.toFixed(1):'—'} label="Müşteri Puanı" note={`${stats.feedbackCount} değerlendirme`}/><Metric icon={<Activity/>} value={String(peak)} label="En Yoğun Gün" note="Görüntülenme"/></div><div className="qaStatsGrid"><section className="qaManageCard qaStatsChart"><div className="qaDashHead"><div><h2>Son 7 Gün</h2><p>QR menü görüntülenmeleri.</p></div><span className="qaStatusPill">7 gün</span></div><MiniChart rows={stats.dailyViews}/></section><section className="qaManageCard"><div className="qaDashHead"><div><h2>En Çok İncelenen Ürünler</h2><p>Ürün ilgisine göre sıralama.</p></div></div><div className="qaStatProducts">{stats.topProducts.map((p,i)=><div key={p.id}><b>{i+1}</b><img src={p.image||'/makarilla_tabak.png'} alt=""/><span>{p.name}</span><strong>{p.views}</strong></div>)}</div></section><section className="qaManageCard qaInsightCard"><h2>Hızlı İçgörü</h2><div><span>Toplam görüntülenme</span><b>{stats.totalViews}</b></div><div><span>Bugünkü pay</span><b>{stats.totalViews?Math.round(stats.todayViews/stats.totalViews*100):0}%</b></div><div><span>Bekleyen çağrı</span><b>{stats.pendingCalls}</b></div></section></div></div>}
function SettingsSection({restaurant,save}:{restaurant:Restaurant;save:(r:Restaurant)=>void}){const[d,setD]=useState(restaurant);return <div className="qaPage"><Title title="Ayarlar" sub="QR menünün görünüm ve bağlantı ayarları." action={<button className="qaAdd" onClick={()=>save(d)}><Save/>Kaydet</button>}/><div className="qaFormCards"><section className="qaManageCard"><h2>Marka Görünümü</h2><Field label="Logo URL" value={d.logo} set={v=>setD({...d,logo:v})}/><label>Tema Rengi<input type="color" value={d.themeColor||'#f46861'} onChange={e=>setD({...d,themeColor:e.target.value})}/></label><div className="qaThemePreview" style={{background:d.themeColor||'#f46861'}}>{d.name}</div></section><section className="qaManageCard"><h2>Bağlantılar</h2><Field label="Instagram" value={d.instagram} set={v=>setD({...d,instagram:v})}/><Field label="Yol Tarifi URL" value={d.directionsUrl} set={v=>setD({...d,directionsUrl:v})}/><p className="qaNote">Giriş/şifre ve kullanıcı yetkilendirmesi güvenlik aşamasında ayrıca bağlanacak.</p></section></div></div>}
function ago(v:string){const m=Math.max(0,Math.round((Date.now()-new Date(v).getTime())/60000));return m<1?'Şimdi':m<60?`${m} dk önce`:`${Math.floor(m/60)} sa önce`}
function Editor({p,cats,isNew,close,save,del}:{p:Product;cats:Category[];isNew:boolean;close:()=>void;save:(p:Product)=>void;del:(id:string)=>void}){const[d,setD]=useState(p);return <div className="qaEditorBackdrop"><section className="qaEditor"><header><button onClick={close}><ChevronLeft/></button><h2>{isNew?'Ürün Ekle':'Ürün Düzenle'}</h2><button disabled={isNew} onClick={()=>del(d.id)}><Trash2/></button></header><div className="qaEditorPhoto"><img src={d.image||'/makarilla_tabak.png'} alt=""/></div><label>Ürün Adı<input value={d.name} onChange={e=>setD({...d,name:e.target.value})}/></label><label>Açıklama<textarea value={d.description} onChange={e=>setD({...d,description:e.target.value})}/></label><label>Görsel URL<input value={d.image} onChange={e=>setD({...d,image:e.target.value})}/></label><div className="qaFormGrid"><label>Kategori<select value={d.categoryId} onChange={e=>setD({...d,categoryId:e.target.value})}>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Fiyat<div className="qaPrice"><span>₺</span><input type="number" value={d.price} onChange={e=>setD({...d,price:Number(e.target.value)})}/></div></label></div><div className="qaVisibility"><span>Menüde Göster</span><button className={d.isActive?'qaToggle on':'qaToggle'} onClick={()=>setD({...d,isActive:!d.isActive})}><i/></button></div><button className="qaSave" disabled={!d.name.trim()} onClick={()=>save({...d,name:d.name.trim()})}>Değişiklikleri Kaydet</button></section></div>}
