'use client';
import './premium-v2.css';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {LayoutDashboard,Utensils,Tags,QrCode,Store,MessageSquare,BellRing,Settings,ExternalLink,Plus,Search,Eye,MoreHorizontal,TrendingUp,ChevronDown,Star,Clock3,CheckCircle2,GripVertical} from 'lucide-react';
type Tab='overview'|'products'|'categories'|'restaurant'|'waiter'|'feedback'|'qr'|'settings';
const products=[{name:'Bolonez Makarna',cat:'Makarnalar',price:299,desc:'Dana bolonez sos, parmesan',img:'🍝'},{name:'Alfredo Makarna',cat:'Makarnalar',price:289,desc:'Krema, parmesan, özel sos',img:'🍜'},{name:'Tavuklu Pesto Penne',cat:'Tavuklu Makarnalar',price:319,desc:'Tavuk, pesto, parmesan',img:'🥘'},{name:'Tavuklu Alfredo Penne',cat:'Tavuklu Makarnalar',price:329,desc:'Tavuk, krema, parmesan',img:'🍲'}];
const nav=[['overview','Genel Bakış',LayoutDashboard],['products','Ürünler',Utensils],['categories','Kategoriler',Tags],['restaurant','Restoran Bilgileri',Store],['waiter','Garson Çağrıları',BellRing],['feedback','Geri Bildirimler',MessageSquare],['qr','QR Kod',QrCode],['settings','Ayarlar',Settings]] as const;
export default function Admin(){const[tab,setTab]=useState<Tab>('overview');const[q,setQ]=useState('');const filtered=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase())),[q]);const title=nav.find(n=>n[0]===tab)?.[1]||'Genel Bakış';return <main className="ptAdminPremium"><header className="ptTop"><div className="ptLogo">panel<span>takip</span><small>QR MENÜ</small></div><div className="ptTopRight"><button className="ptBranch"><span className="ptBranchMark">M</span><span><b>Makarilla</b><small>Karşıyaka · İzmir</small></span><ChevronDown size={15}/></button><button className="ptBell"><BellRing size={17}/><i>2</i></button><Link href="/menu/makarilla" target="_blank" className="ptView"><Eye size={16}/>Menüyü Gör<ExternalLink size={13}/></Link><div className="ptAvatar">MK</div></div></header><div className="ptShell"><aside className="ptSide"><div className="ptSideTitle">ÇALIŞMA ALANI</div>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={tab===id?'ptNav isActive':'ptNav'}><Icon size={18}/><span>{label}</span>{id==='waiter'&&<em>2</em>}</button>)}<div className="ptSideFoot"><div className="ptPlan"><small>PANELTAKİP PRO</small><b>QR Menü aktif</b><span><i/> Sistem çalışıyor</span></div></div></aside><section className="ptContent"><div className="ptPageHead"><div><p>MAKARILLA <span>/</span> QR MENÜ</p><h1>{title}</h1></div>{tab==='products'&&<button className="ptPrimary"><Plus size={16}/>Yeni Ürün</button>}{tab==='categories'&&<button className="ptPrimary"><Plus size={16}/>Yeni Kategori</button>}</div>{tab==='overview'?<Overview setTab={setTab}/>:tab==='products'?<Products q={q} setQ={setQ} items={filtered}/>:tab==='feedback'?<Feedback/>:tab==='categories'?<Categories/>:<Empty tab={tab}/>}</section></div></main>}
function Overview({setTab}:{setTab:(t:Tab)=>void}){return <><div className="ptStats"><Stat k="Bugünkü Görüntülenme" v="184" s="+18%" note="düne göre"/><Stat k="Menü Ürünleri" v="24" s="22 aktif" note="2 pasif"/><Stat k="Müşteri Puanı" v="4.8" s="96 yorum" note="son 30 gün"/><Stat k="Bekleyen Çağrı" v="2" s="Masa 5 · Masa 8" note="işlem bekliyor" warn/></div><div className="ptDashboardGrid"><div className="ptPanel ptPerformance"><div className="ptPanelHead row"><div><h2>Menü performansı</h2><p>Son 7 gündeki QR menü görüntülenmeleri</p></div><button>Son 7 gün <ChevronDown size={14}/></button></div><div className="ptChart"><div className="ptChartValue"><strong>1.248</strong><span><TrendingUp size={13}/> %14,2 artış</span></div><div className="ptBars">{[42,58,47,72,63,88,76].map((h,i)=><div key={i}><i style={{height:h+'%'}}/><span>{['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'][i]}</span></div>)}</div></div></div><div className="ptPanel ptCalls"><div className="ptPanelHead row"><div><h2>Canlı çağrılar</h2><p>Şu anda işlem bekleyenler</p></div><span className="ptLive"><i/> CANLI</span></div><Call table="Masa 5" time="2 dk"/><Call table="Masa 8" time="5 dk"/><button className="ptTextBtn" onClick={()=>setTab('waiter')}>Tüm çağrıları görüntüle →</button></div><div className="ptPanel ptQuickPanel"><div className="ptPanelHead"><h2>Hızlı yönetim</h2><p>Sık kullandığınız işlemlere doğrudan ulaşın.</p></div><div className="ptQuick"><Quick icon={<Utensils/>} t="Ürünleri Yönet" s="Fiyat, görsel ve durum" onClick={()=>setTab('products')}/><Quick icon={<Tags/>} t="Kategoriler" s="Sıralama ve görünürlük" onClick={()=>setTab('categories')}/><Quick icon={<QrCode/>} t="QR Kod" s="Kalıcı menü QR kodu" onClick={()=>setTab('qr')}/><Quick icon={<Store/>} t="Restoran Bilgileri" s="Saat, telefon ve adres" onClick={()=>setTab('restaurant')}/></div></div><div className="ptPanel ptReviewsMini"><div className="ptPanelHead row"><div><h2>Son geri bildirimler</h2><p>Müşterileriniz ne söylüyor?</p></div><button onClick={()=>setTab('feedback')}>Tümü</button></div><ReviewMini stars={5} text="Makarnalar çok güzeldi, servis de hızlıydı." time="12 dk önce"/><ReviewMini stars={4} text="Menü çok kullanışlı, ürün görselleri başarılı." time="1 sa önce"/></div></div></>}
function Stat({k,v,s,note,warn}:{k:string,v:string,s:string,note:string,warn?:boolean}){return <div className={'ptStat '+(warn?'warn':'')}><div className="ptStatTop"><span>{k}</span><i className="ptStatDot"/></div><strong>{v}</strong><div className="ptStatFoot"><b>{s}</b><span>{note}</span></div></div>}
function Call({table,time}:{table:string,time:string}){return <div className="ptCall"><div className="ptCallIcon"><BellRing size={17}/></div><div><b>{table}</b><span>Garson çağrısı · {time} önce</span></div><button>Yanıtla</button></div>}
function Quick({icon,t,s,onClick}:{icon:React.ReactNode,t:string,s:string,onClick:()=>void}){return <button onClick={onClick}><i>{icon}</i><div><b>{t}</b><span>{s}</span></div><strong>→</strong></button>}
function ReviewMini({stars,text,time}:{stars:number,text:string,time:string}){return <div className="ptReviewMini"><div><span>{Array.from({length:stars}).map((_,i)=><Star key={i} size={12} fill="currentColor"/>)}</span><small>{time}</small></div><p>{text}</p></div>}
function Products({q,setQ,items}:{q:string,setQ:(v:string)=>void,items:typeof products}){return <><div className="ptToolbar"><label><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ürün adı veya kategori ara..."/></label><div><button>Tüm kategoriler <ChevronDown size={14}/></button><button>Durum <ChevronDown size={14}/></button></div></div><div className="ptPanel ptTable"><div className="ptTableTop"><div><h2>Tüm ürünler</h2><p>24 ürün · 22 aktif</p></div><button>Sıralamayı düzenle</button></div><div className="ptThead"><span>ÜRÜN</span><span>KATEGORİ</span><span>FİYAT</span><span>DURUM</span><span/></div>{items.map((p,i)=><div className="ptTr" key={p.name}><div className="ptProd"><div className={'ptThumb t'+i}>{p.img}</div><div><b>{p.name}</b><small>{p.desc}</small></div></div><span>{p.cat}</span><b>₺{p.price}</b><span className="ptBadge"><i/>Aktif</span><button className="ptMore"><MoreHorizontal size={18}/></button></div>)}</div></>}
function Feedback(){return <div className="ptFeedbackGrid"><div className="ptPanel ptRating"><small>GENEL PUAN</small><div><strong>4.8</strong><span>{[1,2,3,4,5].map(i=><Star key={i} size={19} fill="currentColor"/>)}</span><p>96 doğrulanmış geri bildirim</p></div></div><div className="ptPanel ptDistribution"><div className="ptPanelHead"><h2>Puan dağılımı</h2><p>Son 30 gün</p></div>{[[5,78],[4,14],[3,5],[2,2],[1,1]].map(([s,p])=><div className="ptRate" key={s}><span>{s} <Star size={11} fill="currentColor"/></span><i><b style={{width:p+'%'}}/></i><em>%{p}</em></div>)}</div><div className="ptPanel ptFeedbackList"><div className="ptPanelHead row"><div><h2>Müşteri yorumları</h2><p>En yeni geri bildirimler</p></div><button>Filtrele</button></div><FullReview name="Misafir · Masa 12" stars={5} text="Makarnalar gerçekten çok başarılıydı. QR menü hızlı açıldı ve ürünleri bulmak çok kolaydı." time="Bugün, 19:42"/><FullReview name="Misafir · Masa 4" stars={5} text="Servis hızlı, menü çok şık. Tekrar geleceğiz." time="Bugün, 18:16"/><FullReview name="Misafir · Masa 7" stars={4} text="Her şey güzeldi. Tatlı seçenekleri biraz daha fazla olabilir." time="Dün, 21:08"/></div></div>}
function FullReview({name,stars,text,time}:{name:string,stars:number,text:string,time:string}){return <div className="ptFullReview"><div className="ptReviewer">{name.slice(-2)}</div><div><div className="ptReviewHead"><b>{name}</b><span>{Array.from({length:stars}).map((_,i)=><Star key={i} size={12} fill="currentColor"/>)}</span><small>{time}</small></div><p>{text}</p></div></div>}
function Categories(){const cats=[['Makarnalar',8,'Yayında'],['Tavuklu Makarnalar',6,'Yayında'],['Salatalar',4,'Yayında'],['Wraplar',3,'Yayında'],['Tatlılar',2,'Yayında'],['İçecekler',1,'Yayında']];return <div className="ptPanel ptCategoryPanel"><div className="ptTableTop"><div><h2>Menü kategorileri</h2><p>Sürükleyerek menü sırasını değiştirebilirsiniz.</p></div></div>{cats.map(([n,c,s])=><div className="ptCategoryRow" key={String(n)}><GripVertical size={18}/><div className="ptCatIcon"><Tags size={18}/></div><div><b>{n}</b><span>{c} ürün</span></div><span className="ptBadge"><i/>{s}</span><button className="ptMore"><MoreHorizontal size={18}/></button></div>)}</div>}
function Empty({tab}:{tab:Tab}){const tx:Record<string,string>={restaurant:'Logo, restoran adı, çalışma saatleri, telefon ve adres.',waiter:'Masa bazlı garson çağrılarını anlık yönetin.',qr:'Restoranın kalıcı QR kodunu görüntüleyin ve indirin.',settings:'QR menü ve restoran çalışma alanı ayarları.'};return <div className="ptPanel ptEmpty"><div><CheckCircle2/></div><h2>{nav.find(n=>n[0]===tab)?.[1]}</h2><p>{tx[tab]}</p><span>Bu modül sonraki aşamada detaylandırılacak.</span></div>}
